"""End-code descriptions, generated from ``aslmp/data/end_codes.tsv``.

@generated by ``tools/gen_endcodes.py``. **Do not edit this file.** Edit the TSV and
run ``python tools/gen_endcodes.py --write``; CI asserts that regenerating is a
byte-for-byte no-op.

Layer 0.5. Imports ``aslmp.wire.citations`` and nothing else.

:data:`END_CODES` is an open record table, not a closed enum: a code that is absent
from it still raises a named exception carrying ``0x%04X`` formatting and a request to
report it, because the error path is exactly where a second failure is unaffordable.

Three rows carry :attr:`~aslmp.wire.citations.Provenance.LIVE` provenance because the
hardware contradicted the manuals: ``0xC05C`` (not ``0xC05B``) for a device family the
CPU does not have, ``0xC052`` for a zero point count, and ``0xC061`` (not ``0xC057``)
for a request-length mismatch. Their notes say what the documents led us to expect.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Final

from aslmp.wire.citations import Citation, Measurement, Provenance, Source

__all__ = ["END_CODES", "EndCodeInfo"]


@dataclass(frozen=True, slots=True)
class EndCodeInfo:
    """One row of the end-code table.

    ``exception_class`` is the NAME of a class in :mod:`aslmp.errors`, or ``""`` when
    the code has no dedicated subclass and raises the base ``SlmpEndCodeError``. It is
    a string rather than a class object so that this module stays below the hand-written
    hierarchy and cannot import it.
    """

    code: int
    name: str
    exception_class: str
    description: str
    likely_cause: str
    caller_action: str
    provenance: Provenance
    citation: Citation | None
    measurement: Measurement | None
    note: str

    @property
    def source(self) -> Source:
        """The authoritative provenance: the measurement if there is one."""
        if self.measurement is not None:
            return self.measurement
        if self.citation is None:
            raise ValueError(
                f"end code 0x{self.code:04X} has neither a citation nor a measurement"
            )
        return self.citation

    @property
    def documented(self) -> bool:
        """False for a code synthesised at run time for something we have never seen."""
        return True


END_CODES: Final[Mapping[int, EndCodeInfo]] = {
    0x0000: EndCodeInfo(
        code=0x0000,
        name="normal_completion",
        exception_class="",
        description="Normal completion.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "Never raises. Present so that a decoder can look 0x0000 up like any other code "
            "instead of special-casing a falsy value."
        ),
    ),
    0x4000: EndCodeInfo(
        code=0x4000,
        name="cpu_sum_check_error",
        exception_class="SlmpCpuError",
        description="Common error: serial communication sum check error.",
        likely_cause="Serial MC protocol only; 3E/4E over Ethernet carry no sum check.",
        caller_action="Not reachable from this library.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4001: EndCodeInfo(
        code=0x4001,
        name="cpu_unsupported_request",
        exception_class="SlmpCpuUnsupportedRequestError",
        description="Common error: an unsupported request was executed.",
        likely_cause="The CPU does not implement this request.",
        caller_action="Check the command data and the CPU model.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4002: EndCodeInfo(
        code=0x4002,
        name="cpu_unsupported_request_2",
        exception_class="SlmpCpuUnsupportedRequestError",
        description="Common error: an unsupported request was executed.",
        likely_cause="The CPU serial number may not support the function.",
        caller_action="Check the command data and the CPU serial number.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4005: EndCodeInfo(
        code=0x4005,
        name="cpu_data_too_large",
        exception_class="SlmpCpuDataTooLargeError",
        description=(
            "Common error: the volume of data handled for the specified request is too large."
        ),
        likely_cause="",
        caller_action="Reduce the request.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4006: EndCodeInfo(
        code=0x4006,
        name="cpu_initial_communication_failed",
        exception_class="SlmpCpuError",
        description="Common error: initial communication has failed.",
        likely_cause="",
        caller_action="Shift the communication start timing.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4010: EndCodeInfo(
        code=0x4010,
        name="cpu_running",
        exception_class="SlmpCpuRunningError",
        description=(
            "CPU module operation error: since the CPU module is running, the request contents "
            "cannot be executed."
        ),
        likely_cause="This is the FX5's write-during-RUN refusal.",
        caller_action="Set the CPU to STOP.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4013: EndCodeInfo(
        code=0x4013,
        name="cpu_not_stopped",
        exception_class="SlmpCpuRunningError",
        description=(
            "CPU module operation error: since the CPU module is not in STOP, the request "
            "contents cannot be executed."
        ),
        likely_cause="",
        caller_action="Set the CPU to STOP.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4021: EndCodeInfo(
        code=0x4021,
        name="cpu_drive_error",
        exception_class="SlmpCpuFileError",
        description=(
            "File related error: the specified drive does not exist, or there is an error in "
            "it."
        ),
        likely_cause="",
        caller_action="Check the drive.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4022: EndCodeInfo(
        code=0x4022,
        name="cpu_file_not_found",
        exception_class="SlmpCpuFileError",
        description=(
            "File related error: the file with the specified name or number does not exist."
        ),
        likely_cause="",
        caller_action="Check the file.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4025: EndCodeInfo(
        code=0x4025,
        name="cpu_file_in_use",
        exception_class="SlmpCpuFileError",
        description=(
            "File related error: the specified file is processing a request from another "
            "engineering tool."
        ),
        likely_cause="",
        caller_action="Retry later.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4027: EndCodeInfo(
        code=0x4027,
        name="cpu_range_larger_than_file",
        exception_class="SlmpCpuFileError",
        description="File related error: the specified range is larger than the file size.",
        likely_cause="",
        caller_action="Reduce the range.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4029: EndCodeInfo(
        code=0x4029,
        name="cpu_file_capacity",
        exception_class="SlmpCpuFileError",
        description="File related error: the specified file capacity cannot be obtained.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x402C: EndCodeInfo(
        code=0x402C,
        name="cpu_operation_not_currently_possible",
        exception_class="SlmpCpuFileError",
        description=(
            "File related error: the requested operation cannot be executed at the moment."
        ),
        likely_cause="",
        caller_action="Retry after a while.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4030: EndCodeInfo(
        code=0x4030,
        name="cpu_device_name_error",
        exception_class="SlmpCpuDeviceSpecError",
        description="Device specification error: the specified device name cannot be handled.",
        likely_cause="",
        caller_action="Check the device code.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4031: EndCodeInfo(
        code=0x4031,
        name="cpu_device_number_out_of_range",
        exception_class="SlmpCpuDeviceSpecError",
        description=(
            "Device specification error: the specified device number is outside the range, or "
            "the CPU module cannot handle the specified device."
        ),
        likely_cause="The second half of the address-range story, alongside 0xC056.",
        caller_action="Check the device number against the CPU's device assignment.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4032: EndCodeInfo(
        code=0x4032,
        name="cpu_device_modification_error",
        exception_class="SlmpCpuDeviceSpecError",
        description=(
            "Device specification error: the device modification was incorrectly specified, or "
            "an unusable device (TS, TC, SS, SC, CS or CC) was specified in Read Random, Write "
            "Random in word units, Entry Monitor Device or Execute Monitor."
        ),
        likely_cause="Contacts or coils in a random or monitor command.",
        caller_action="Use the current-value device (TN, STN, CN) instead.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "Documented but NOT enforced: an FX5U-32MT/DS fw 1.065 accepted a 0403 with a TS0 "
            "word point and answered 0x0000 with data. See A-TS-IN-RANDOM."
        ),
    ),
    0x4034: EndCodeInfo(
        code=0x4034,
        name="cpu_completion_device_off",
        exception_class="SlmpCpuError",
        description=(
            "Device specification error: the completion device for a dedicated instruction did "
            "not turn on."
        ),
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4040: EndCodeInfo(
        code=0x4040,
        name="cpu_module_request_error",
        exception_class="SlmpCpuModuleError",
        description=(
            "Intelligent function module specification error: the request cannot be executed "
            "in the specified module."
        ),
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4041: EndCodeInfo(
        code=0x4041,
        name="cpu_module_range_error",
        exception_class="SlmpCpuModuleError",
        description=(
            "Intelligent function module specification error: the access range exceeds the "
            "buffer memory range of the specified module."
        ),
        likely_cause="",
        caller_action="Reduce the range.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4042: EndCodeInfo(
        code=0x4042,
        name="cpu_module_not_accessible",
        exception_class="SlmpCpuModuleError",
        description=(
            "Intelligent function module specification error: the specified module cannot be "
            "accessed."
        ),
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4043: EndCodeInfo(
        code=0x4043,
        name="cpu_module_absent",
        exception_class="SlmpCpuModuleError",
        description=(
            "Intelligent function module specification error: there is no intelligent function "
            "module at the specified position."
        ),
        likely_cause="",
        caller_action="Check the I/O number.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4053: EndCodeInfo(
        code=0x4053,
        name="cpu_drive_write_error",
        exception_class="SlmpCpuError",
        description="Protect error: an error occurred when writing to the specified drive.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4060: EndCodeInfo(
        code=0x4060,
        name="cpu_online_debug_in_use",
        exception_class="SlmpCpuError",
        description=(
            "Online registration error: online debug or data logging is in use by another "
            "engineering tool."
        ),
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4064: EndCodeInfo(
        code=0x4064,
        name="cpu_online_change_incorrect",
        exception_class="SlmpCpuError",
        description=(
            "Online registration error: the contents of the online change, logging, memory "
            "dump or real-time monitor are incorrect."
        ),
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4068: EndCodeInfo(
        code=0x4068,
        name="cpu_operation_disabled",
        exception_class="SlmpCpuError",
        description=(
            "Online registration error: the operation is disabled because it is being "
            "performed with another engineering tool."
        ),
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4080: EndCodeInfo(
        code=0x4080,
        name="cpu_request_data_error",
        exception_class="SlmpCpuError",
        description="Other error: request data error.",
        likely_cause="",
        caller_action="Check the request data.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x4081: EndCodeInfo(
        code=0x4081,
        name="cpu_search_target_not_found",
        exception_class="SlmpCpuError",
        description="Other error: the search target data cannot be detected.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x408B: EndCodeInfo(
        code=0x408B,
        name="cpu_remote_request_refused",
        exception_class="SlmpCpuRemoteDisabledError",
        description="Other error: the remote request cannot be executed.",
        likely_cause=(
            "Remote Reset is disabled in the CPU parameters. That is the DEFAULT on a fresh "
            "FX5U, and the single most likely reason a 1006 fails."
        ),
        caller_action=(
            "Enable Remote Reset in GX Works3 under CPU Parameter, Operation Related Setting, "
            "then re-execute once the CPU can accept it."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x40A0: EndCodeInfo(
        code=0x40A0,
        name="cpu_sfc_block_error",
        exception_class="SlmpCpuError",
        description="SFC device specification error: the block number is out of range.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x40A1: EndCodeInfo(
        code=0x40A1,
        name="cpu_sfc_block_error_2",
        exception_class="SlmpCpuError",
        description="SFC device specification error: the block number is out of range.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x40A7: EndCodeInfo(
        code=0x40A7,
        name="cpu_sfc_step_error",
        exception_class="SlmpCpuError",
        description="SFC device specification error: the step number is out of range.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x40A8: EndCodeInfo(
        code=0x40A8,
        name="cpu_sfc_step_error_2",
        exception_class="SlmpCpuError",
        description="SFC device specification error: the step number is out of range.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x40B0: EndCodeInfo(
        code=0x40B0,
        name="cpu_sfc_file_error",
        exception_class="SlmpCpuError",
        description="SFC file related error.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0x40B1: EndCodeInfo(
        code=0x40B1,
        name="cpu_sfc_file_error_2",
        exception_class="SlmpCpuError",
        description="SFC file related error.",
        likely_cause="",
        caller_action="",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="JY997D55401",
            revision="unknown",
            section="Appendix 3, Error codes of the CPU module (4000H to 4FFFH) (p.593)",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC001: EndCodeInfo(
        code=0xC001,
        name="initial_setting_error",
        exception_class="SlmpConnectionStateError",
        description=(
            "The IP address for initial processing is incorrect, or the router-relay subnet "
            "mask setting is wrong."
        ),
        likely_cause="PLC-side Ethernet parameters.",
        caller_action="Fix the CPU's Ethernet parameters in GX Works3.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC012: EndCodeInfo(
        code=0xC012,
        name="tcp_port_already_open",
        exception_class="SlmpConnectionStateError",
        description=(
            "The port number of a connection that is already open was specified (TCP/IP)."
        ),
        likely_cause="Two connection entries claim the same port.",
        caller_action="Change the port.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC013: EndCodeInfo(
        code=0xC013,
        name="udp_port_already_open",
        exception_class="SlmpConnectionStateError",
        description=(
            "The port number of a connection that is already open was specified (UDP/IP)."
        ),
        likely_cause="Two connection entries claim the same port.",
        caller_action="Change the port.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC015: EndCodeInfo(
        code=0xC015,
        name="external_ip_incorrect",
        exception_class="SlmpConnectionStateError",
        description="The specified IP address of the external device is incorrect.",
        likely_cause="The connection entry's destination IP does not match this host.",
        caller_action="Fix the destination IP in the connection entry.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "A UDP SLMP connection entry on iQ-F is point to point: GX Works3 refuses to save "
            "it without a destination IP, so every UDP peer needs its own entry."
        ),
    ),
    0xC018: EndCodeInfo(
        code=0xC018,
        name="external_ip_incorrect_2",
        exception_class="SlmpConnectionStateError",
        description="The specified IP address of the external device is incorrect.",
        likely_cause="As 0xC015.",
        caller_action="Fix the destination IP.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC020: EndCodeInfo(
        code=0xC020,
        name="message_too_long",
        exception_class="SlmpDataLengthError",
        description="The send or receive data length exceeds the allowable range.",
        likely_cause="The frame is larger than the module will accept.",
        caller_action="Split the request into several transactions.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC021: EndCodeInfo(
        code=0xC021,
        name="fixed_buffer_abnormal_end",
        exception_class="",
        description=(
            "An abnormal end response was received for fixed-buffer or random-access-buffer "
            "communications."
        ),
        likely_cause="Wrong subheader, or a communication-data-code mismatch.",
        caller_action="Check the binary/ASCII setting of the connection entry.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC022: EndCodeInfo(
        code=0xC022,
        name="response_timer_expired",
        exception_class="SlmpPlcTimeoutError",
        description=(
            "A response could not be received within the response monitoring timer, or the "
            "connection was closed while waiting."
        ),
        likely_cause="The access destination did not answer.",
        caller_action=(
            "Surface the timeout. Do not retry silently: for a write, the outcome is unknown."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC035: EndCodeInfo(
        code=0xC035,
        name="alive_check_failed",
        exception_class="SlmpPlcTimeoutError",
        description=(
            "The existence of the external device could not be confirmed within the response "
            "monitoring timer."
        ),
        likely_cause="The alive check failed.",
        caller_action="Check the link.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC040: EndCodeInfo(
        code=0xC040,
        name="incomplete_receive",
        exception_class="SlmpPlcTimeoutError",
        description=(
            "Not all of the data could be received within the response monitoring timer; the "
            "declared data length never arrived."
        ),
        likely_cause="A truncated message.",
        caller_action="Check the request data length arithmetic and resend.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC050: EndCodeInfo(
        code=0xC050,
        name="ascii_conversion_error",
        exception_class="SlmpAsciiConversionError",
        description=(
            "With the communication data code set to ASCII, data arrived that cannot be "
            "converted to binary."
        ),
        likely_cause="Binary was sent to an ASCII-configured entry, or the ASCII is malformed.",
        caller_action=(
            "Match the client's encoding to the connection entry's Communication Data Code."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "The mirror-image mistake, ASCII into a BINARY entry, is 0xC06F and produces "
            "SILENCE rather than this code."
        ),
    ),
    0xC051: EndCodeInfo(
        code=0xC051,
        name="bit_batch_point_count",
        exception_class="SlmpBitPointCountError",
        description=(
            "The number of bit devices for a batch read or write is outside the allowable "
            "range."
        ),
        likely_cause="Too many bit points in one 0401/1401.",
        caller_action=(
            "Reduce the point count. aslmp refuses over the profile's limit before sending."
        ),
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "Binary-searched: 3584 bit points from M0 returned 0x0000 and 3585 returned "
            "0xC051. SH(NA)-080956ENG-M's generic ceiling is 7168, exactly double, so a client "
            "that hard-codes the SLMP-REF figure builds frames this CPU rejects. See "
            "A-BATCH-BIT-LIMIT."
        ),
    ),
    0xC052: EndCodeInfo(
        code=0xC052,
        name="word_batch_point_count",
        exception_class="SlmpWordPointCountError",
        description=(
            "The number of word devices for a batch read or write is outside the allowable "
            "range."
        ),
        likely_cause="Too many word points in one 0401/1401 -- or ZERO points.",
        caller_action="Reduce the point count. A zero point count is refused client-side.",
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "MEASURED CORRECTION: a request for ZERO word points returned 0xC052, not the "
            "address error our doc-derived mapping predicted. 961 word points from D0 also "
            "returned 0xC052; 960 succeeded. Reconfirmed over UDP. See A-ZERO-POINT-COUNT."
        ),
    ),
    0xC053: EndCodeInfo(
        code=0xC053,
        name="bit_random_point_count",
        exception_class="SlmpRandomPointCountError",
        description=(
            "The number of bit devices for a random read or write is outside the allowable "
            "range."
        ),
        likely_cause="Too many bit points in one 1402.",
        caller_action="Split the request. The iQ-F binary cap is 188 points.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC054: EndCodeInfo(
        code=0xC054,
        name="word_random_point_count",
        exception_class="SlmpRandomPointCountError",
        description=(
            "The number of word or double-word devices for a random read or write is outside "
            "the allowable range."
        ),
        likely_cause="Too many points in one 0403/1402.",
        caller_action=(
            "Split the request, or use allow_split=True and accept that the snapshot atomicity "
            "is lost."
        ),
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "192 word-access points returned 0x0000; 193 returned 0xC054; 255 returned 0xC054. "
            "The constraint is word_points + dword_points <= 192, independent of how many "
            "words come back. The point-count fields are one byte each, so the wire format "
            "will not stop you."
        ),
    ),
    0xC055: EndCodeInfo(
        code=0xC055,
        name="file_size_out_of_range",
        exception_class="SlmpDataLengthError",
        description="The read or write size for file data is outside the allowable range.",
        likely_cause="File commands only.",
        caller_action="Reduce the byte count.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC056: EndCodeInfo(
        code=0xC056,
        name="address_out_of_range",
        exception_class="SlmpDeviceRangeError",
        description="The read or write request exceeds the maximum address.",
        likely_cause=(
            "The head address, or the head address plus the point count, falls outside the "
            "device area this CPU has configured."
        ),
        caller_action=(
            "Fix the start address or the point count. This is the code check_range exists to "
            "prevent."
        ),
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "D8000 with 1 point returned 0xC056 and D7999 with 1 point returned 0x0000, "
            "confirming D0-D7999. D7999 with TWO points also returned 0xC056 -- the span, not "
            "the start address, is what is checked, which is why check_range takes the point "
            "count. D99999 also returned 0xC056."
        ),
    ),
    0xC057: EndCodeInfo(
        code=0xC057,
        name="request_length_mismatch",
        exception_class="SlmpPlcFramingError",
        description=(
            "The request data length in the SLMP message does not match the amount of data in "
            "the character section."
        ),
        likely_cause="The L field is wrong.",
        caller_action="Fix the length arithmetic.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "Documented, but an FX5U-32MT/DS fw 1.065 returns 0xC061 for this condition, not "
            "0xC057. See A-C061-NOT-C057."
        ),
    ),
    0xC058: EndCodeInfo(
        code=0xC058,
        name="ascii_request_length_mismatch",
        exception_class="SlmpPlcFramingError",
        description=(
            "The request data length after ASCII-to-binary conversion does not match the "
            "amount of data in the character section."
        ),
        likely_cause="The ASCII L field is wrong.",
        caller_action=(
            "Compute the length per codec: an ASCII bit-data length is not twice the binary "
            "one when the point count is odd."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC059: EndCodeInfo(
        code=0xC059,
        name="command_or_subcommand_error",
        exception_class="SlmpUnsupportedCommandError",
        description=(
            "Error in command or subcommand specification. There is a command or subcommand "
            "that cannot be used by the CPU module."
        ),
        likely_cause=(
            "A command this CPU does not implement, or a subcommand from the wrong device "
            "specification family."
        ),
        caller_action="Use a command the target supports, and check the CPU firmware version.",
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "Measured four ways on this CPU: 0801 Monitor Registration, 0802 Execute Monitor, "
            "subcommand 0x0002 (the iQ-R long device specification) and the nonsense command "
            "0x9999 all returned 0xC059. Note 0802 returns 0xC059 and not 0xC05D, so there is "
            "no way to mistake it for 'you forgot to register'."
        ),
    ),
    0xC05A: EndCodeInfo(
        code=0xC05A,
        name="device_not_accessible",
        exception_class="SlmpDeviceNotAccessibleError",
        description=(
            "The module cannot read or write data from or to the device specified in the SLMP "
            "message."
        ),
        likely_cause="A device code this CPU does not support.",
        caller_action="Use a device this CPU has.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC05B: EndCodeInfo(
        code=0xC05B,
        name="device_not_accessible_2",
        exception_class="SlmpDeviceNotAccessibleError",
        description="The module cannot read or write data from or to the specified device.",
        likely_cause=(
            "The documented code for a device the CPU does not have, such as V or ZR on an "
            "FX5, or a local device."
        ),
        caller_action="Use a device this CPU has.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "An FX5U-32MT/DS fw 1.065 returns 0xC05C for this condition instead. This row is "
            "kept because an iQ-R may well behave as documented. See A-C05C-NOT-C05B."
        ),
    ),
    0xC05C: EndCodeInfo(
        code=0xC05C,
        name="request_content_error",
        exception_class="SlmpRequestContentError",
        description=(
            "Error in request contents, for example a read or write by bit unit addressed to a "
            "word device."
        ),
        likely_cause=(
            "On an FX5, most often a device family this CPU does not have (V, ZR, DX, DY) or a "
            "device code byte that is not a device code at all. Otherwise, the wrong bit-0 "
            "subcommand for the device type."
        ),
        caller_action=(
            "Check the device exists on this CPU. aslmp's device table refuses the absent "
            "families before the frame is built, so you should not see this for that reason."
        ),
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "MEASURED CORRECTION: device code 0x00, device code 0xFF, V0, ZR0 and DX0 all "
            "returned 0xC05C, where the doc-derived mapping predicted 0xC05B. Without this "
            "correction the library tells a user their subcommand is wrong when their CPU "
            "simply has no edge relays. See A-C05C-NOT-C05B."
        ),
    ),
    0xC05D: EndCodeInfo(
        code=0xC05D,
        name="monitor_not_registered",
        exception_class="SlmpMonitorNotRegisteredError",
        description=(
            "An Execute Monitor request arrived before Monitor Registration was performed."
        ),
        likely_cause="0802 was sent without a preceding 0801.",
        caller_action="Register the device list first.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="Unreachable on iQ-F, which refuses 0802 itself with 0xC059.",
    ),
    0xC05E: EndCodeInfo(
        code=0xC05E,
        name="cpu_communication_timeout",
        exception_class="SlmpPlcTimeoutError",
        description=(
            "The communication time between the module and the CPU, or to the access "
            "destination, exceeded the monitoring timer set in the SLMP request."
        ),
        likely_cause="The request's monitoring timer is too small, or the route is slow.",
        caller_action=(
            "Increase the request's monitoring timer field, which is independent of the "
            "client-side deadline."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC05F: EndCodeInfo(
        code=0xC05F,
        name="request_not_executable",
        exception_class="SlmpRoutingError",
        description=(
            "This request cannot be executed against the target CPU module or access "
            "destination."
        ),
        likely_cause="Wrong network number, station number or module I/O number.",
        caller_action="Fix the route bytes.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC060: EndCodeInfo(
        code=0xC060,
        name="bit_device_data_error",
        exception_class="SlmpRequestContentError",
        description=(
            "Error in request contents, for example an error in the data specified for a bit "
            "device."
        ),
        likely_cause="The bit-write payload is malformed; the nibble packing is wrong.",
        caller_action=(
            "Two points per byte, first point in the high nibble, odd counts padded low."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC061: EndCodeInfo(
        code=0xC061,
        name="request_data_length_mismatch",
        exception_class="SlmpPlcFramingError",
        description=(
            "The request data length does not match the amount of data in the character "
            "section."
        ),
        likely_cause="The L field does not match the body that followed it.",
        caller_action="Compute L in one place from the encoded body.",
        provenance=Provenance.LIVE,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=Measurement(
            cpu="FX5U-32MT/DS",
            firmware="1.065",
            date="2026-09-06",
        ),
        note=(
            "MEASURED CORRECTION: this, not 0xC057, is the framing code this CPU returns. "
            "Understating L by 2 returned 0xC061 and the connection recovered. Declaring "
            "L=0x0000 returned 0xC061 with the command and subcommand echoed as 0x0000. "
            "OVERSTATING L produced NO RESPONSE AT ALL: the CPU blocks waiting for bytes that "
            "never arrive, which is indistinguishable from a dead PLC. See A-C061-NOT-C057."
        ),
    ),
    0xC062: EndCodeInfo(
        code=0xC062,
        name="write_protected_during_run",
        exception_class="SlmpWriteProtectedError",
        description="Writing was prohibited while the CPU was running.",
        likely_cause=(
            "Enable Online Change is off, or a QnA-compatible 3E/4E write was addressed to a "
            "remote I/O station."
        ),
        caller_action="Enable online change in the CPU parameters, or put the CPU in STOP.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC06F: EndCodeInfo(
        code=0xC06F,
        name="ascii_into_binary_entry",
        exception_class="",
        description=(
            "With the communication data code set to Binary, an ASCII request message was "
            "received. The error history is registered but NO ERROR RESPONSE IS SENT."
        ),
        likely_cause="The client is speaking ASCII to a binary-configured connection entry.",
        caller_action=(
            "Match the encoding to the entry's Communication Data Code. There is nothing to "
            "retry: the code never reaches the wire."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "This row will never be constructed from a response, because there is no response. "
            "It exists so that SlmpTimeoutError.likely_causes can name it: on a first "
            "transaction with zero bytes received, a coding mismatch is the leading suspect. "
            "Confirmed on FX5U-32MT/DS fw 1.065: a well-formed 42-character ASCII 3E request "
            "produced no bytes at all for 4000 ms, the connection stayed open with no FIN, and "
            "a fresh binary request immediately afterwards worked."
        ),
    ),
    0xC070: EndCodeInfo(
        code=0xC070,
        name="device_memory_not_extendable",
        exception_class="",
        description="The device memory cannot be extended for the access destination.",
        likely_cause="The extension subcommand was sent to a target that does not support it.",
        caller_action="Drop the device-memory-extension bit.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC071: EndCodeInfo(
        code=0xC071,
        name="point_count_out_of_range",
        exception_class="SlmpPointCountError",
        description=(
            "The number of device points for a read or write set for a module other than an "
            "R/Q/QnA CPU is out of range."
        ),
        likely_cause="Too many points for this target.",
        caller_action="Reduce the point count.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC072: EndCodeInfo(
        code=0xC072,
        name="request_details_incorrect",
        exception_class="SlmpRequestContentError",
        description=(
            "The request details are incorrect; for example a bit-unit read or write was "
            "issued to a word device."
        ),
        likely_cause="The subcommand's unit bit does not match the device.",
        caller_action="Fix the subcommand.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC073: EndCodeInfo(
        code=0xC073,
        name="destination_cannot_execute",
        exception_class="SlmpRoutingError",
        description=(
            "The access destination cannot execute this request; for example double-word "
            "access points cannot be specified for a module other than an R/Q/QnA CPU."
        ),
        likely_cause="Double-word random access to a target that does not support it.",
        caller_action="Use word access points.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC074: EndCodeInfo(
        code=0xC074,
        name="target_cannot_execute",
        exception_class="SlmpRoutingError",
        description="This request cannot be executed against the target CPU module.",
        likely_cause="Wrong network or PC number.",
        caller_action="Fix the route bytes.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC075: EndCodeInfo(
        code=0xC075,
        name="label_request_length",
        exception_class="SlmpDataLengthError",
        description="The request data length for label access is out of range.",
        likely_cause="Label commands only.",
        caller_action="Shorten the label list.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0B2: EndCodeInfo(
        code=0xC0B2,
        name="receive_buffer_full",
        exception_class="SlmpBusyError",
        description=(
            "There is no space in the receive buffer of the relay or destination station."
        ),
        likely_cause="The PLC is being given more than it can take.",
        caller_action=(
            "Increase the interval between requests and wait for each response. Never "
            "auto-retried by this library."
        ),
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0B3: EndCodeInfo(
        code=0xC0B3,
        name="cpu_cannot_process_request",
        exception_class="",
        description="A request that cannot be processed was issued from the CPU module.",
        likely_cause="",
        caller_action="Fix the request or the routing.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0B5: EndCodeInfo(
        code=0xC0B5,
        name="unprocessable_data",
        exception_class="SlmpRequestContentError",
        description=(
            "Data that cannot be processed by the CPU module or the Ethernet module was "
            "specified."
        ),
        likely_cause="",
        caller_action="Correct the request and cancel the current one.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note=(
            "Present in the Q/L list and absent from the iQ-R list, which goes 0xC0B3 to "
            "0xC0B6. It is a Q/L E71-era code."
        ),
    ),
    0xC0B6: EndCodeInfo(
        code=0xC0B6,
        name="channel_number_out_of_range",
        exception_class="",
        description="The channel number is outside the allowable range.",
        likely_cause="A dedicated-instruction path, not an SLMP client.",
        caller_action="Use channel 1 to 8.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0B9: EndCodeInfo(
        code=0xC0B9,
        name="tcp_open_not_complete",
        exception_class="SlmpConnectionStateError",
        description="The TCP open processing is not complete.",
        likely_cause="Connection lifecycle.",
        caller_action="Reopen the connection.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0BA: EndCodeInfo(
        code=0xC0BA,
        name="tcp_close_in_progress",
        exception_class="SlmpConnectionStateError",
        description="TCP close processing is in progress.",
        likely_cause="Connection lifecycle.",
        caller_action="Wait for the close to finish, then reopen.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0BC: EndCodeInfo(
        code=0xC0BC,
        name="line_closed",
        exception_class="SlmpConnectionStateError",
        description="The specified line is closed.",
        likely_cause="Connection lifecycle.",
        caller_action="Reopen the connection.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0BD: EndCodeInfo(
        code=0xC0BD,
        name="successive_requests",
        exception_class="SlmpBusyError",
        description="Requests were accepted successively and cannot be processed.",
        likely_cause="The client is overrunning the module.",
        caller_action="Throttle. Never auto-retried.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081105ENG",
            revision="G",
            section="16.7.1 End codes returned to an external device",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0D8: EndCodeInfo(
        code=0xC0D8,
        name="block_count_out_of_range",
        exception_class="SlmpPointCountError",
        description="The number of specified blocks exceeds the allowable range.",
        likely_cause="Too many blocks in one 0406/1406.",
        caller_action="Reduce the block count.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0D9: EndCodeInfo(
        code=0xC0D9,
        name="subcommand_incorrect",
        exception_class="SlmpUnsupportedCommandError",
        description="The specified subcommand of the SLMP message is incorrect.",
        likely_cause="",
        caller_action="Fix the subcommand.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC0DE: EndCodeInfo(
        code=0xC0DE,
        name="arrival_monitoring_timeout",
        exception_class="SlmpPlcTimeoutError",
        description="Data could not be received within the specified arrival monitoring time.",
        likely_cause="",
        caller_action="Increase the timer.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1A4: EndCodeInfo(
        code=0xC1A4,
        name="command_subcommand_or_io_incorrect",
        exception_class="SlmpUnsupportedCommandError",
        description=(
            "The command, subcommand or request destination module I/O number is incorrect, or "
            "the function is not supported by the target device."
        ),
        likely_cause="The routed-access cousin of 0xC059.",
        caller_action="Check the command, the subcommand and the destination I/O number.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1A5: EndCodeInfo(
        code=0xC1A5,
        name="target_or_clear_target_incorrect",
        exception_class="SlmpRoutingError",
        description="The specified target station or clear target is incorrect.",
        likely_cause="",
        caller_action="Fix the target.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1A6: EndCodeInfo(
        code=0xC1A6,
        name="connection_number_incorrect",
        exception_class="",
        description="The specified connection number is incorrect.",
        likely_cause="",
        caller_action="Fix the connection number.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1A7: EndCodeInfo(
        code=0xC1A7,
        name="network_number_incorrect",
        exception_class="SlmpRoutingError",
        description="The specified network number is incorrect.",
        likely_cause="",
        caller_action="Fix the route bytes.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1A8: EndCodeInfo(
        code=0xC1A8,
        name="station_number_incorrect",
        exception_class="SlmpRoutingError",
        description="The specified station number is incorrect.",
        likely_cause="",
        caller_action="Fix the route bytes.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1A9: EndCodeInfo(
        code=0xC1A9,
        name="device_number_incorrect",
        exception_class="SlmpDeviceRangeError",
        description="The specified device number is incorrect.",
        likely_cause="",
        caller_action="Fix the address.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC1AA: EndCodeInfo(
        code=0xC1AA,
        name="device_name_incorrect",
        exception_class="SlmpDeviceNotAccessibleError",
        description="The specified device name is incorrect.",
        likely_cause="",
        caller_action="Fix the device code.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC200: EndCodeInfo(
        code=0xC200,
        name="remote_password_incorrect",
        exception_class="SlmpRemotePasswordError",
        description="The remote password is incorrect.",
        likely_cause="Wrong password on unlock or lock.",
        caller_action="Correct the password and re-run the unlock.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC201: EndCodeInfo(
        code=0xC201,
        name="remote_password_locked",
        exception_class="SlmpRemotePasswordLockedError",
        description="The remote password status of the port used for communications is locked.",
        likely_cause="Nothing else can be done until the port is unlocked.",
        caller_action="Send 1630 Remote Password Unlock first.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC202: EndCodeInfo(
        code=0xC202,
        name="remote_password_other_station",
        exception_class="SlmpRemotePasswordError",
        description=(
            "When another station was accessed, the remote password could not be unlocked."
        ),
        likely_cause="Routed access through a password-protected relay.",
        caller_action="Remove the password on the relay or access station.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC203: EndCodeInfo(
        code=0xC203,
        name="remote_password_check_error",
        exception_class="SlmpRemotePasswordError",
        description="An error occurred while checking the remote password.",
        likely_cause="",
        caller_action="Unlock again.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC204: EndCodeInfo(
        code=0xC204,
        name="remote_password_wrong_device",
        exception_class="SlmpRemotePasswordError",
        description=(
            "The device is different from the one that requested the remote password unlock."
        ),
        likely_cause="A different IP is trying to use a session somebody else unlocked.",
        caller_action="Lock and unlock from the same device.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC205: EndCodeInfo(
        code=0xC205,
        name="remote_password_other_station_2",
        exception_class="SlmpRemotePasswordError",
        description=(
            "When another station was accessed, the remote password could not be unlocked."
        ),
        likely_cause="As 0xC202.",
        caller_action="Remove the password on the relay or access station.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC810: EndCodeInfo(
        code=0xC810,
        name="remote_password_failures_under_10",
        exception_class="SlmpRemotePasswordError",
        description=(
            "Error in the remote password; the authentication failure count is 9 or less."
        ),
        likely_cause="",
        caller_action="Correct the password and retry.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC815: EndCodeInfo(
        code=0xC815,
        name="remote_password_failures_10",
        exception_class="SlmpRemotePasswordLockoutError",
        description=(
            "Error in the remote password; the authentication failure count has reached 10."
        ),
        likely_cause="",
        caller_action="Wait out the lockout time.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC816: EndCodeInfo(
        code=0xC816,
        name="remote_password_locked_out",
        exception_class="SlmpRemotePasswordLockoutError",
        description="Remote password authentication is locked out.",
        likely_cause="",
        caller_action="Wait out the lockout time.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xC86C: EndCodeInfo(
        code=0xC86C,
        name="too_many_simultaneous_requests",
        exception_class="SlmpBusyError",
        description=(
            "The number of received request messages exceeded the number that can be received "
            "simultaneously (64 per port)."
        ),
        likely_cause="Too many concurrent requests.",
        caller_action="Throttle. Never auto-retried.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xCEE0: EndCodeInfo(
        code=0xCEE0,
        name="iqss_detection_in_progress",
        exception_class="",
        description=(
            "An iQ Sensor Solution function was executed while automatic detection of "
            "connected devices was in progress."
        ),
        likely_cause="iQSS only.",
        caller_action="Wait for detection to finish.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xCEE1: EndCodeInfo(
        code=0xCEE1,
        name="iqss_incorrect_frame",
        exception_class="",
        description="An incorrect frame was received.",
        likely_cause="iQSS target device.",
        caller_action="Check the target device and the cabling.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xCEE2: EndCodeInfo(
        code=0xCEE2,
        name="iqss_incorrect_frame_2",
        exception_class="",
        description="An incorrect frame was received.",
        likely_cause="iQSS target device.",
        caller_action="Check the target device and the cabling.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xCF10: EndCodeInfo(
        code=0xCF10,
        name="iqss_incorrect_frame_3",
        exception_class="",
        description="An incorrect frame was received.",
        likely_cause="iQSS.",
        caller_action="Check the target device.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
    0xCF20: EndCodeInfo(
        code=0xCF20,
        name="iqss_setting_out_of_range",
        exception_class="",
        description=(
            "The communication setting value is out of range, an unsettable item was set, or a "
            "required item was left unset."
        ),
        likely_cause="iQSS.",
        caller_action="Fix the setting.",
        provenance=Provenance.MANUAL,
        citation=Citation(
            manual="SH(NA)-081257ENG",
            revision="AD",
            section="3.5 List of Error Codes",
            provenance=Provenance.MANUAL,
        ),
        measurement=None,
        note="",
    ),
}
