"""Shared reporting for the bench scripts. Not part of the wheel.

**The one rule this module enforces: no table without a control.**
:func:`report` raises :class:`MissingControlError` unless it is handed at least one
distribution measured through a raw socket in the same session. That is not a style
preference. The same machine, the same PLC and the same Wi-Fi link produced p50 7.1 /
p99 18.8 ms on one afternoon and p50 10.3 / p99 95.2 ms on another, with nothing changed
but the day. A library latency number with no control beside it does not say what the
library costs; it says what the link was doing while the library ran.

**Two controls, one before and one after.** The drift between them is the honest error
bar on everything in between, and it is usually larger than the thing being measured.

Everything here writes Markdown, because these numbers end up in a README, an issue or
an email, and a table that has to be reformatted to be shared gets summarised into a
mean instead.
"""

from __future__ import annotations

import platform
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass

from aslmp.tools.bench import Distribution, nearest_rank

__all__ = ["MissingControlError", "Row", "report"]


class MissingControlError(RuntimeError):
    """Raised when a report was assembled with no same-session raw-socket control."""


@dataclass(frozen=True, slots=True)
class Row:
    """One measured thing, and whether it was measured through this library.

    ``control=True`` means the samples came from a bare socket that shares no code with
    ``aslmp``. At least one such row is required for the report to exist at all.
    """

    distribution: Distribution
    control: bool = False


def _cells(row: Row) -> list[str]:
    dist = row.distribution
    label = f"**{dist.label}**" if row.control else dist.label
    if not dist.samples:
        return [label, "0", "--", "--", "--", "--", "--", "--", dist.note]
    ordered = dist.ordered
    return [
        label,
        str(dist.n),
        f"{ordered[0]:.2f}",
        f"{nearest_rank(ordered, 50):.2f}",
        f"{nearest_rank(ordered, 90):.2f}",
        f"{nearest_rank(ordered, 99):.2f}",
        f"{ordered[-1]:.2f}",
        f"{dist.stdev:.2f}",
        dist.note,
    ]


_HEADER = ("measurement", "n", "min", "p50", "p90", "p99", "max", "stdev", "note")


def report(title: str, rows: Sequence[Row], *, target: str) -> str:
    """A Markdown section for one run, or raise because it has no control.

    ``target`` names the CPU, the entry and the link, because a distribution without
    those is not reproducible and should not be quoted.
    """
    controls = [row for row in rows if row.control]
    if not controls:
        raise MissingControlError(
            "this report has no same-session raw-socket control row. Every published "
            "number in this repository carries one, because the same rig moved 5x at "
            "p99 between two afternoons. Measure the control, or publish nothing."
        )
    if not any(control.distribution.samples for control in controls):
        raise MissingControlError(
            "the control row carries no samples: the raw socket never completed a "
            "transaction, so nothing here has a baseline"
        )

    lines = [
        f"### {title}",
        "",
        f"Target: {target}",
        f"Host: {platform.platform()}, Python {sys.version.split()[0]}",
        f"Run: {time.strftime('%Y-%m-%d %H:%M:%S %z')}",
        "",
        "All times in milliseconds. **Bold rows are the raw-socket control** -- a bare "
        "blocking socket, hand-built 3E binary frames, no `aslmp` code on the path.",
        "",
        "| " + " | ".join(_HEADER) + " |",
        "| " + " | ".join("---" for _ in _HEADER) + " |",
    ]
    lines.extend("| " + " | ".join(_cells(row)) + " |" for row in rows)

    if len(controls) >= 2:
        first = controls[0].distribution
        last = controls[-1].distribution
        if first.samples and last.samples:
            before = nearest_rank(first.ordered, 50)
            after = nearest_rank(last.ordered, 50)
            lines += [
                "",
                f"Control drift across the run: p50 {before:.2f} -> {after:.2f} ms "
                f"({abs(after - before):.2f} ms). Read that number before any other: it "
                f"is the error bar on everything between the two control rows, and on a "
                f"real plant network it is often larger than the library's own overhead.",
            ]
    return "\n".join(lines) + "\n"


def preamble(what: str) -> str:
    """The paragraph every generated report starts with. Nobody may quote a row without it."""
    return (
        f"# {what}\n"
        "\n"
        "Generated by a script in `bench/`. Every table below carries a same-session\n"
        "raw-socket control, and the numbers are only comparable **within** one table:\n"
        "different runs of this file on different days are not comparable to each other,\n"
        "which is exactly what the control rows are there to show you.\n"
        "\n"
        "These are distributions, not means. For a control loop the tail is the number\n"
        "that decides whether a cadence holds; the median is the number that flatters a\n"
        "README.\n"
    )
