#!/usr/bin/env python
"""Generate ``aslmp/timed.py`` from ``aslmp/client.py``'s AST.

DESIGN.md graft G14 wants two surfaces: ``plc.read_f32("D0")`` gives a bare ``float``,
because ``.value`` on every line forever is the wrong tax on a library whose main job is
reading one float; and ``plc.timed.read_f32("D0")`` gives a
:class:`~aslmp.results.Reading` carrying the transaction, because a control loop that
cannot see ``wire_ms`` is worse. Section 4.8 says how the duplication stays honest: the
second surface is **generated from the first and committed**, and CI asserts that
regenerating it is a byte-for-byte no-op.

**What it copies, and why textually.** Every ``Plc`` method wearing ``@mirrored`` is
copied verbatim from the source text -- signature, docstring and body, with its original
line breaks -- and exactly three edits are applied, each located by the AST rather than
by a regular expression:

1. every ``self`` becomes ``self._plc``;
2. ``self._done(value, tx)`` becomes ``Reading(value, tx)`` and ``self._ack(points, tx)``
   becomes ``WriteAck(points, tx)`` -- those two one-line helpers are the entire seam
   between the surfaces;
3. the return annotation becomes ``Reading[...]`` or ``WriteAck``.

``ast.unparse`` would have been shorter and is wrong here: it re-emits every docstring as
one escaped line and every statement as one long line, so the generated file would be
unreadable, would not fit in 96 columns, and every diff would be a wall. The point of
committing generated code is that a person reads it.

Usage::

    python tools/gen_timed.py            # check the committed file is current
    python tools/gen_timed.py --write    # regenerate it
    python tools/gen_timed.py --stdout   # print what it would write

``--check`` (the default) is the CI gate, asserted by
``tests/unit/test_client.py::test_the_committed_timed_module_matches_the_generator``.
"""

from __future__ import annotations

import argparse
import ast
import builtins
import difflib
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "src" / "aslmp" / "client.py"
TARGET = REPO_ROOT / "src" / "aslmp" / "timed.py"
WIDTH = 96
MARKER = "mirrored"
"""The decorator that marks a ``Plc`` method as belonging to the timed surface."""

HEADER = '''\
"""The same calls as :class:`aslmp.client.Plc`, returning the transaction with the value.

@generated by ``tools/gen_timed.py`` from ``aslmp/client.py``. **Do not edit this file.**
Edit the method on ``Plc``, mark it ``@mirrored``, and run
``python tools/gen_timed.py --write``; CI asserts that regenerating is a byte-for-byte
no-op, which is what stops the two surfaces from drifting.

Layer 5, and a peer of :mod:`aslmp.client` rather than a layer above it: this module
imports the client, and ``Plc.timed`` resolves this one lazily on first use.

DESIGN.md graft G14. The primary surface returns bare values; this one returns
:class:`~aslmp.results.Reading` for a read and :class:`~aslmp.results.WriteAck` for a
write. Both are the same code: ``Plc._done`` and ``Plc._ack`` are one-line helpers on the
client whose only job is to be the seam a generator can cut along.

One consequence worth knowing: :class:`~aslmp.results.RandomReading` carries its own
``tx`` field (DESIGN.md section 2.6), so ``plc.timed.read_random(...)`` returns a
``Reading[RandomReading]`` whose ``.tx`` is the same object as its ``.value.tx``. The
uniformity is deliberate -- ``tests/unit/test_client.py`` asserts that the two surfaces
have identical public method names and parameter lists, and an exception carved out here
would be an exception to maintain by hand.
"""
'''

CLASS_HEADER = '''

class TimedApi:
    """``plc.timed``: every :class:`~aslmp.client.Plc` call, with its record attached.

    Not constructed directly. ``Plc.timed`` builds one on first use and caches it, so a
    control loop that reaches for it every cycle allocates nothing.
    """

    __slots__ = ("_plc",)

    def __init__(self, plc: Plc) -> None:
        self._plc = plc

    @property
    def plc(self) -> Plc:
        """The client these calls run on. The bare-value surface for the same socket."""
        return self._plc
'''

_BUILTINS = frozenset(dir(builtins))
_ALWAYS_IMPORT = {
    "Plc": "aslmp.client",
    "Reading": "aslmp.results",
    "WriteAck": "aslmp.results",
}


def fail(message: str) -> None:
    """Refuse to write a file rather than write one that is subtly wrong."""
    raise SystemExit(f"tools/gen_timed.py: {message}")


# ----------------------------------------------------------------------------------------
# What client.py makes available under each name
# ----------------------------------------------------------------------------------------


def name_sources(tree: ast.Module) -> dict[str, str]:
    """Every module-level name in ``client.py``, mapped to the module it comes from.

    An imported name maps to the module it was imported from, so ``timed.py`` imports it
    from the same place rather than through the client; a name *defined* in ``client.py``
    maps to ``aslmp.client``. Plain ``import x`` maps ``x`` to the sentinel ``""``, which
    is emitted as ``import x``.
    """
    sources: dict[str, str] = dict(_ALWAYS_IMPORT)
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.asname is not None:
                    fail(f"`import {alias.name} as {alias.asname}` is not supported")
                sources[alias.name.split(".")[0]] = ""
        elif isinstance(node, ast.ImportFrom):
            if node.module is None or node.level:
                fail("relative imports are not supported in client.py")
            if node.module == "__future__":
                continue
            for alias in node.names:
                sources.setdefault(alias.asname or alias.name, node.module)
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
            sources.setdefault(node.name, "aslmp.client")
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    sources.setdefault(target.id, "aslmp.client")
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            sources.setdefault(node.target.id, "aslmp.client")
    for node in ast.walk(tree):
        if isinstance(node, ast.If) and _is_type_checking(node.test):
            for inner in node.body:
                if isinstance(inner, ast.ImportFrom) and inner.module is not None:
                    for alias in inner.names:
                        sources.setdefault(alias.asname or alias.name, inner.module)
    return sources


def _is_type_checking(test: ast.expr) -> bool:
    return isinstance(test, ast.Name) and test.id == "TYPE_CHECKING"


# ----------------------------------------------------------------------------------------
# Locating what to copy
# ----------------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Method:
    """One method to mirror: its ``@overload`` stubs and its implementation."""

    name: str
    overloads: tuple[ast.AsyncFunctionDef, ...]
    implementation: ast.AsyncFunctionDef


def decorator_names(node: ast.AsyncFunctionDef) -> set[str]:
    names: set[str] = set()
    for decorator in node.decorator_list:
        if isinstance(decorator, ast.Name):
            names.add(decorator.id)
        elif isinstance(decorator, ast.Attribute):
            names.add(decorator.attr)
    return names


def collect(tree: ast.Module) -> list[Method]:
    """Every ``@mirrored`` method of ``class Plc``, in source order, with its overloads."""
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == "Plc":
            plc = node
            break
    else:  # pragma: no cover - client.py always defines it
        fail("client.py has no `class Plc`")
    methods: list[Method] = []
    pending: list[ast.AsyncFunctionDef] = []
    for item in plc.body:
        if not isinstance(item, ast.AsyncFunctionDef):
            pending.clear()
            continue
        decorators = decorator_names(item)
        if "overload" in decorators:
            pending.append(item)
            continue
        if MARKER not in decorators:
            pending.clear()
            continue
        overloads = tuple(stub for stub in pending if stub.name == item.name)
        pending.clear()
        methods.append(Method(item.name, overloads, item))
    if not methods:
        fail(f"no method of class Plc carries @{MARKER}")
    return methods


# ----------------------------------------------------------------------------------------
# The three edits
# ----------------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Edit:
    """A byte-span replacement in the source, keyed by (line, column) so it can sort."""

    lineno: int
    col: int
    end_lineno: int
    end_col: int
    text: str


def span_of(node: ast.expr) -> tuple[int, int, int, int]:
    if node.end_lineno is None or node.end_col_offset is None:  # pragma: no cover
        fail(f"node at line {node.lineno} has no end position")
        raise AssertionError  # unreachable; fail() raises
    return (node.lineno, node.col_offset, node.end_lineno, node.end_col_offset)


def seam_of(node: ast.AsyncFunctionDef) -> str:
    """Which seam helper this method returns through: ``_done`` or ``_ack``.

    A method that calls neither cannot be mirrored, because there would be nothing to
    attach the transaction to; a method that calls both would need two return types.
    Either is a build failure with a sentence rather than a plausible wrong file.
    """
    seams = {
        call.func.attr
        for call in ast.walk(node)
        if isinstance(call, ast.Call)
        and isinstance(call.func, ast.Attribute)
        and isinstance(call.func.value, ast.Name)
        and call.func.value.id == "self"
        and call.func.attr in ("_done", "_ack")
    }
    if len(seams) != 1:
        fail(
            f"Plc.{node.name} is marked @{MARKER} but returns through {sorted(seams)}. "
            f"Every mirrored method returns through exactly one of self._done(value, tx) "
            f"or self._ack(points, tx): those two helpers are the seam this generator "
            f"cuts along, and a method with neither has no transaction to hand back."
        )
    return seams.pop()


def timed_return(annotation: ast.expr | None, seam: str) -> str:
    """The mirrored return type. A read gains ``Reading[...]``; a write becomes an ack.

    A union is distributed rather than wrapped: ``RandomReading | SplitReading`` becomes
    ``Reading[RandomReading] | Reading[SplitReading]``, not
    ``Reading[RandomReading | SplitReading]``. It is the more precise type -- one reading
    is one of the two, never a value of the union -- and it is the only form an
    ``@overload`` on ``Literal[True]`` type-checks against, because ``Reading`` is
    invariant in its parameter and a caller who passed ``allow_split=False`` must not be
    handed a union to narrow.
    """
    if seam == "_ack":
        return "WriteAck"
    if annotation is None:  # pragma: no cover - refused earlier
        return "Reading[None]"
    parts = _union_members(annotation)
    return " | ".join(f"Reading[{ast.unparse(part)}]" for part in parts)


def _union_members(annotation: ast.expr) -> list[ast.expr]:
    """The top-level members of ``A | B | C``, or ``[annotation]`` if it is not a union."""
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return _union_members(annotation.left) + _union_members(annotation.right)
    return [annotation]


def edits_for(node: ast.AsyncFunctionDef, seam: str, *, stub: bool) -> list[Edit]:
    """The replacements that turn one copied method into its mirrored twin."""
    edits: list[Edit] = []
    if node.returns is None:
        fail(f"Plc.{node.name} has no return annotation")
        raise AssertionError  # unreachable
    line, col, end_line, end_col = span_of(node.returns)
    edits.append(Edit(line, col, end_line, end_col, "<RETURN>"))
    if stub:
        return edits
    seam_funcs: set[int] = set()
    for call in ast.walk(node):
        if (
            isinstance(call, ast.Call)
            and isinstance(call.func, ast.Attribute)
            and isinstance(call.func.value, ast.Name)
            and call.func.value.id == "self"
            and call.func.attr in ("_done", "_ack")
        ):
            seam_funcs.add(id(call.func.value))
            replacement = "Reading" if call.func.attr == "_done" else "WriteAck"
            edits.append(Edit(*span_of(call.func), replacement))
    for inner in ast.walk(node):
        if isinstance(inner, ast.Name) and inner.id == "self" and id(inner) not in seam_funcs:
            edits.append(Edit(*span_of(inner), "self._plc"))
    del seam
    return edits


def apply_edits(lines: list[str], node: ast.AsyncFunctionDef, edits: list[Edit]) -> str:
    """Copy ``node``'s source lines with ``edits`` applied, right to left, bottom to top.

    Right to left so that an earlier edit never moves a later edit's column, and the
    ``@mirrored`` decorator line is simply never copied: the slice starts at ``async``.
    """
    start = node.lineno
    end = node.end_lineno
    if end is None:  # pragma: no cover - every function has an end
        fail(f"Plc.{node.name} has no end line")
        raise AssertionError
    block = lines[start - 1 : end]
    for edit in sorted(edits, key=lambda e: (e.lineno, e.col), reverse=True):
        if edit.lineno != edit.end_lineno:
            fail(
                f"Plc.{node.name}: the generator only rewrites spans that fit on one "
                f"line, and the one at line {edit.lineno} does not. Reformat it in "
                f"client.py so that the return annotation and every `self` sit on a "
                f"single line."
            )
        index = edit.lineno - start
        text = block[index]
        block[index] = text[: edit.col] + edit.text + text[edit.end_col :]
    return "\n".join(block)


def render_method(source_lines: list[str], method: Method) -> str:
    """One method's mirrored source: its overload stubs, then its implementation."""
    seam = seam_of(method.implementation)
    parts: list[str] = []
    for stub in method.overloads:
        rendered = apply_edits(source_lines, stub, edits_for(stub, seam, stub=True))
        body = rendered.replace("<RETURN>", timed_return(stub.returns, seam))
        parts.append("    @overload\n" + body)
    node = method.implementation
    rendered = apply_edits(source_lines, node, edits_for(node, seam, stub=False))
    parts.append(rendered.replace("<RETURN>", timed_return(node.returns, seam)))
    return "\n\n".join(parts)


# ----------------------------------------------------------------------------------------
# Imports
# ----------------------------------------------------------------------------------------


def referenced(text: str) -> set[str]:
    """Every bare name the generated body mentions, parsed rather than grepped."""
    tree = ast.parse(f"class _Probe:\n{text}\n")
    return {node.id for node in ast.walk(tree) if isinstance(node, ast.Name)}


def import_block(names: set[str], sources: dict[str, str]) -> str:
    """The import section of the generated module, in ``ruff``'s isort order."""
    plain: set[str] = set()
    grouped: dict[str, set[str]] = {}
    for name in sorted(names):
        if name in _BUILTINS or name not in sources:
            continue
        module = sources[name]
        if module == "":
            plain.add(name)
        else:
            grouped.setdefault(module, set()).add(name)
    stdlib_plain = sorted(plain)
    first_party = {m: n for m, n in grouped.items() if m.split(".")[0] == "aslmp"}
    stdlib_from = {m: n for m, n in grouped.items() if m.split(".")[0] != "aslmp"}
    lines = ["from __future__ import annotations", ""]
    lines += [f"import {name}" for name in stdlib_plain]
    lines += [_from_line(module, stdlib_from[module]) for module in sorted(stdlib_from)]
    lines.append("")
    lines += [_from_line(module, first_party[module]) for module in sorted(first_party)]
    return "\n".join(lines)


def _member_key(name: str) -> tuple[int, str]:
    """``ruff``'s isort ``order-by-type``: constants, then classes, then everything else.

    Within a group the order is case-insensitive. The classification is on the **raw**
    name, leading underscore included, which is why ``_RawCommand`` sorts with the
    functions rather than with the classes -- its first character is not uppercase. That
    detail is not a guess: it is what ``ruff check --fix --select I`` does to this file,
    and reimplementing it here rather than shelling out is what keeps the generator
    deterministic without a formatter installed.
    """
    if name.isupper():
        return (0, name.lower())
    if name[:1].isupper():
        return (1, name.lower())
    return (2, name.lower())


def _from_line(module: str, names: set[str]) -> str:
    """``from x import a, b``, wrapped in parentheses when it does not fit 96 columns."""
    ordered = sorted(names, key=_member_key)
    single = f"from {module} import {', '.join(ordered)}"
    if len(single) <= WIDTH:
        return single
    body = "".join(f"    {name},\n" for name in ordered)
    return f"from {module} import (\n{body})"


# ----------------------------------------------------------------------------------------
# Rendering
# ----------------------------------------------------------------------------------------


def render() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source, filename=str(SOURCE))
    sources = name_sources(tree)
    methods = collect(tree)
    bodies = [render_method(lines, method) for method in methods]
    joined = "\n\n".join(bodies)
    names = referenced(joined) | {"Plc", "Reading", "WriteAck"}
    if any(method.overloads for method in methods):
        names.add("overload")
    text = "\n".join(
        [
            HEADER.rstrip("\n"),
            "",
            import_block(names, sources),
            "",
            '__all__ = ["TimedApi"]',
            CLASS_HEADER.rstrip("\n"),
            "",
            joined,
            "",
        ]
    )
    _check_width(text)
    return text


def _check_width(text: str) -> None:
    """Refuse to emit a file ``ruff`` would reject, and say which source line to shorten.

    Every ``self`` in a copied body grows by five characters, so a line that fits in
    ``client.py`` can overflow here. The fix is always in ``client.py``: shorten the
    source line. Failing here rather than committing an over-long file keeps the
    generated module lintable like any other.
    """
    over = [
        f"line {number}: {len(line)} columns -- {line.strip()[:60]}"
        for number, line in enumerate(text.splitlines(), start=1)
        if len(line) > WIDTH
    ]
    if over:
        fail(
            "the generated file would not fit in "
            f"{WIDTH} columns. Shorten the corresponding line in client.py:\n  "
            + "\n  ".join(over)
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate aslmp/timed.py from client.py")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="rewrite the committed file")
    group.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv)

    generated = render()
    if args.stdout:
        sys.stdout.write(generated)
        return 0
    if args.write:
        TARGET.write_text(generated, encoding="ascii", newline="\n")
        print(f"wrote {TARGET}")
        return 0
    if not TARGET.exists():
        print(f"{TARGET} does not exist; run: python tools/{Path(__file__).name} --write")
        return 1
    current = TARGET.read_text(encoding="ascii")
    if current == generated:
        print(f"{TARGET} is current")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"{TARGET} (committed)",
            tofile="regenerated from src/aslmp/client.py",
        )
    )
    print(f"\n{TARGET} is stale; run: python tools/{Path(__file__).name} --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
