#!/usr/bin/env python
"""Turn ``aslmp/data/end_codes.tsv`` into the committed ``aslmp/errors/endcodes.py``.

The ~100-row code -> (class, description, cause, action, provenance) mapping is data:
it changes when a manual revision lands, and it must be diffable one row at a time.
The exception CLASS NAMES are not data -- people put them in ``except`` clauses and a
Mitsubishi engineer will read them in the source -- so this generator emits their names
as strings and ``aslmp/errors/routing.py`` resolves them.

Nothing parses a TSV at run time. The error path is the last place that can afford a
second exception, so the table is a literal mapping built at import.

Usage::

    python tools/gen_endcodes.py            # check the committed file is current
    python tools/gen_endcodes.py --write    # regenerate it
    python tools/gen_endcodes.py --stdout   # print what it would write

``--check`` (the default) is the CI gate: regeneration must be a byte-for-byte no-op.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from aslmp.data import Row, read_table  # noqa: E402  (needs the sys.path line above)

TARGET = REPO_ROOT / "src" / "aslmp" / "errors" / "endcodes.py"
WIDTH = 96

HEADER = '''\
"""End-code descriptions, generated from ``aslmp/data/end_codes.tsv``.

@generated by ``tools/gen_endcodes.py``. **Do not edit this file.** Edit the TSV and
run ``python tools/gen_endcodes.py --write``; CI asserts that regenerating is a
byte-for-byte no-op.

Layer 0.5. Imports ``aslmp.wire.citations`` and nothing else.

:data:`END_CODES` is an open record table, not a closed enum: a code that is absent
from it still raises a named exception carrying ``0x%04X`` formatting and a request to
report it, because the error path is exactly where a second failure is unaffordable.

Three rows carry :attr:`~aslmp.wire.citations.Provenance.LIVE` provenance because the
hardware contradicted the manuals: ``0xC05C`` (not ``0xC05B``) for a device family the
CPU does not have, ``0xC052`` for a zero point count, and ``0xC061`` (not ``0xC057``)
for a request-length mismatch. Their notes say what the documents led us to expect.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Final

from aslmp.wire.citations import Citation, Measurement, Provenance, Source

__all__ = ["END_CODES", "EndCodeInfo"]


@dataclass(frozen=True, slots=True)
class EndCodeInfo:
    """One row of the end-code table.

    ``exception_class`` is the NAME of a class in :mod:`aslmp.errors`, or ``""`` when
    the code has no dedicated subclass and raises the base ``SlmpEndCodeError``. It is
    a string rather than a class object so that this module stays below the hand-written
    hierarchy and cannot import it.
    """

    code: int
    name: str
    exception_class: str
    description: str
    likely_cause: str
    caller_action: str
    provenance: Provenance
    citation: Citation | None
    measurement: Measurement | None
    note: str

    @property
    def source(self) -> Source:
        """The authoritative provenance: the measurement if there is one."""
        if self.measurement is not None:
            return self.measurement
        if self.citation is None:
            raise ValueError(
                f"end code 0x{self.code:04X} has neither a citation nor a measurement"
            )
        return self.citation

    @property
    def documented(self) -> bool:
        """False for a code synthesised at run time for something we have never seen."""
        return True


END_CODES: Final[Mapping[int, EndCodeInfo]] = {
'''

FOOTER = "}\n"


def py_str(value: str) -> str:
    """A double-quoted Python literal for an ASCII string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def wrap_str(value: str, indent: int) -> list[str]:
    """Split ``value`` into implicit-concatenation literal lines at ``indent``."""
    pad = " " * indent
    chunks: list[str] = []
    current = ""
    for word in value.split(" "):
        candidate = f"{current} {word}" if current else word
        if current and indent + len(py_str(candidate)) + 1 > WIDTH:
            chunks.append(current + " ")
            current = word
        else:
            current = candidate
    chunks.append(current)
    return [pad + py_str(chunk) for chunk in chunks]


def kw_str(name: str, value: str, indent: int) -> list[str]:
    """Emit ``name="..."`` at ``indent``, wrapping into parentheses when it is long."""
    pad = " " * indent
    single = f"{pad}{name}={py_str(value)},"
    if len(single) <= WIDTH:
        return [single]
    return [f"{pad}{name}=(", *wrap_str(value, indent + 4), f"{pad}),"]


def kw_raw(name: str, value: str, indent: int) -> list[str]:
    """Emit ``name=<expression>,`` at ``indent``."""
    return [f"{' ' * indent}{name}={value},"]


def citation_lines(row: Row, indent: int) -> list[str]:
    if not row["manual"]:
        return kw_raw("citation", "None", indent)
    pad = " " * indent
    inferred = row["provenance"] == "inferred"
    provenance = "Provenance.INFERRED" if inferred else "Provenance.MANUAL"
    body: list[str] = [
        *kw_str("manual", row["manual"], indent + 4),
        *kw_str("revision", row["revision"], indent + 4),
        *kw_str("section", row["section"], indent + 4),
        *kw_raw("provenance", provenance, indent + 4),
    ]
    return [f"{pad}citation=Citation(", *body, f"{pad}),"]


def measurement_lines(row: Row, indent: int) -> list[str]:
    if row["provenance"] != "live":
        return kw_raw("measurement", "None", indent)
    pad = " " * indent
    body = [
        *kw_str("cpu", row["cpu"], indent + 4),
        *kw_str("firmware", row["firmware"], indent + 4),
        *kw_str("date", row["measured"], indent + 4),
    ]
    return [f"{pad}measurement=Measurement(", *body, f"{pad}),"]


def check_row(row: Row) -> None:
    """Refuse to generate from a row that does not carry its own provenance."""
    code = row["code"]
    if row["provenance"] == "live":
        for field in ("cpu", "firmware", "measured"):
            if not row[field]:
                raise SystemExit(
                    f"end_codes.tsv {code}: provenance is live but {field} is empty. "
                    f"A measured fact must name the silicon it was measured on."
                )
    elif row["cpu"] or row["firmware"] or row["measured"]:
        raise SystemExit(
            f"end_codes.tsv {code}: provenance is {row['provenance']!r} but the row "
            f"names a CPU, a firmware or a date."
        )
    if not row["manual"] and row["provenance"] != "live":
        raise SystemExit(f"end_codes.tsv {code}: no manual and no measurement.")
    if row["manual"] and not (row["revision"] and row["section"]):
        raise SystemExit(f"end_codes.tsv {code}: a manual without a revision or section.")
    if not row["description"]:
        raise SystemExit(f"end_codes.tsv {code}: empty description.")


def render() -> str:
    rows = sorted(read_table("end_codes"), key=lambda r: int(r["code"], 16))
    lines: list[str] = [HEADER.rstrip("\n")]
    for row in rows:
        check_row(row)
        code = int(row["code"], 16)
        lines.append(f"    0x{code:04X}: EndCodeInfo(")
        lines.append(f"        code=0x{code:04X},")
        lines.extend(kw_str("name", row["name"], 8))
        lines.extend(kw_str("exception_class", row["exception_class"], 8))
        lines.extend(kw_str("description", row["description"], 8))
        lines.extend(kw_str("likely_cause", row["likely_cause"], 8))
        lines.extend(kw_str("caller_action", row["caller_action"], 8))
        lines.extend(kw_raw("provenance", f"Provenance.{row['provenance'].upper()}", 8))
        lines.extend(citation_lines(row, 8))
        lines.extend(measurement_lines(row, 8))
        lines.extend(kw_str("note", row["note"], 8))
        lines.append("    ),")
    lines.append(FOOTER.rstrip("\n"))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="rewrite the committed file")
    group.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv)

    generated = render()
    if args.stdout:
        sys.stdout.write(generated)
        return 0
    if args.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(generated, encoding="ascii", newline="\n")
        print(f"wrote {TARGET}")
        return 0
    if not TARGET.exists():
        print(f"{TARGET} does not exist; run: python tools/{Path(__file__).name} --write")
        return 1
    current = TARGET.read_text(encoding="ascii")
    if current == generated:
        print(f"{TARGET} is current")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"{TARGET} (committed)",
            tofile="regenerated from data/end_codes.tsv",
        )
    )
    print(f"\n{TARGET} is stale; run: python tools/{Path(__file__).name} --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
