#!/usr/bin/env python
"""Turn ``aslmp/data/devices.tsv`` into the committed ``aslmp/wire/devicetable.py``.

Device codes, ASCII mnemonics, default radices and per-command eligibility are data.
They change when a manual revision lands, they must be diffable one row at a time, and
every one of them has to be checkable against a printed page -- so each row carries its
own citation into the emitted module.

The emitted module is a literal table. ``aslmp.wire`` never parses a TSV, never touches
the filesystem, and never imports ``aslmp.data``.

Usage::

    python tools/gen_devicetable.py            # check the committed file is current
    python tools/gen_devicetable.py --write    # regenerate it
    python tools/gen_devicetable.py --stdout   # print what it would write
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from aslmp.data import Row, read_table  # noqa: E402  (needs the sys.path line above)

TARGET = REPO_ROOT / "src" / "aslmp" / "wire" / "devicetable.py"
WIDTH = 96

RADIX = {"decimal": "Radix.DECIMAL", "hexadecimal": "Radix.HEXADECIMAL", "octal": "Radix.OCTAL"}
UNIT = {"bit": "Unit.BIT", "word": "Unit.WORD"}
SPEC = {"short": "SpecFormat.SHORT", "long": "SpecFormat.LONG"}
BOOL = {"yes": "True", "no": "False"}

HEADER = '''\
"""The SLMP device table, generated from ``aslmp/data/devices.tsv``.

@generated by ``tools/gen_devicetable.py``. **Do not edit this file.** Edit the TSV and
run ``python tools/gen_devicetable.py --write``; CI asserts that regenerating is a
byte-for-byte no-op.

Layer 0. Imports ``citations`` and ``codec``; no filesystem, no ``aslmp.data``.

The table is family-neutral. Which of these devices a given CPU actually HAS, and the
iQ-F override that makes X and Y octal, live in the profile -- because the radix belongs
to the CPU family and not to the letter: ``X1F`` is legal on an iQ-R and a parse error
on an iQ-F.

``random_ok`` is False for the contacts and coils. That is not a restatement of what a
PLC will refuse: an FX5U-32MT/DS on firmware 1.065 ACCEPTED a ``TS0`` word point in a
Read Random and answered end code ``0x0000`` with data, against its own manual. This
column is the only thing that stops it.
"""

from __future__ import annotations

import enum
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Final

from aslmp.wire.citations import Citation, Measurement, Provenance, Source
from aslmp.wire.codec import SpecFormat, Unit

__all__ = ["DEVICE_TABLE", "PREFIXES_LONGEST_FIRST", "DeviceType", "Radix"]


class Radix(enum.IntEnum):
    """The base a device NUMBER is written in. The value is the base, so
    ``int(text, Radix.OCTAL)`` parses an iQ-F X/Y literal directly."""

    OCTAL = 8
    DECIMAL = 10
    HEXADECIMAL = 16


@dataclass(frozen=True, slots=True)
class DeviceType:
    """One device family: how it is named, how it is coded, and where it may be used."""

    name: str
    long_name: str
    unit: Unit
    words_per_point: int
    ascii2: str
    ascii4: str
    code_short: int | None
    code_long: int
    radix: Radix
    min_spec: SpecFormat
    batch_ok: bool
    random_ok: bool
    monitor_ok: bool
    block_ok: bool
    provenance: Provenance
    citation: Citation | None
    measurement: Measurement | None
    note: str

    @property
    def source(self) -> Source:
        """The authoritative provenance: the measurement if there is one."""
        if self.measurement is not None:
            return self.measurement
        if self.citation is None:
            raise ValueError(f"device {self.name} has neither a citation nor a measurement")
        return self.citation


DEVICE_TABLE: Final[Mapping[str, DeviceType]] = {
'''


def py_str(value: str) -> str:
    """A double-quoted Python literal for an ASCII string."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def wrap_str(value: str, indent: int) -> list[str]:
    """Split ``value`` into implicit-concatenation literal lines at ``indent``."""
    pad = " " * indent
    chunks: list[str] = []
    current = ""
    for word in value.split(" "):
        candidate = f"{current} {word}" if current else word
        if current and indent + len(py_str(candidate)) + 1 > WIDTH:
            chunks.append(current + " ")
            current = word
        else:
            current = candidate
    chunks.append(current)
    return [pad + py_str(chunk) for chunk in chunks]


def kw_str(name: str, value: str, indent: int) -> list[str]:
    """Emit ``name="..."`` at ``indent``, wrapping into parentheses when it is long."""
    pad = " " * indent
    single = f"{pad}{name}={py_str(value)},"
    if len(single) <= WIDTH:
        return [single]
    return [f"{pad}{name}=(", *wrap_str(value, indent + 4), f"{pad}),"]


def kw_raw(name: str, value: str, indent: int) -> list[str]:
    """Emit ``name=<expression>,`` at ``indent``."""
    return [f"{' ' * indent}{name}={value},"]


def citation_lines(row: Row, indent: int) -> list[str]:
    if not row["manual"]:
        return kw_raw("citation", "None", indent)
    pad = " " * indent
    inferred = row["provenance"] == "inferred"
    provenance = "Provenance.INFERRED" if inferred else "Provenance.MANUAL"
    body = [
        *kw_str("manual", row["manual"], indent + 4),
        *kw_str("revision", row["revision"], indent + 4),
        *kw_str("section", row["section"], indent + 4),
        *kw_raw("provenance", provenance, indent + 4),
    ]
    return [f"{pad}citation=Citation(", *body, f"{pad}),"]


def measurement_lines(row: Row, indent: int) -> list[str]:
    if row["provenance"] != "live":
        return kw_raw("measurement", "None", indent)
    pad = " " * indent
    body = [
        *kw_str("cpu", row["cpu"], indent + 4),
        *kw_str("firmware", row["firmware"], indent + 4),
        *kw_str("date", row["measured"], indent + 4),
    ]
    return [f"{pad}measurement=Measurement(", *body, f"{pad}),"]


def check_row(row: Row) -> None:
    """Refuse to generate from a row that cannot be checked against a source."""
    name = row["name"]
    if row["provenance"] == "live":
        for field in ("cpu", "firmware", "measured"):
            if not row[field]:
                raise SystemExit(
                    f"devices.tsv {name}: provenance is live but {field} is empty. "
                    f"A measured fact must name the silicon it was measured on."
                )
    elif row["cpu"] or row["firmware"] or row["measured"]:
        raise SystemExit(
            f"devices.tsv {name}: provenance is {row['provenance']!r} but the row names "
            f"a CPU, a firmware or a date."
        )
    if not row["manual"] and row["provenance"] != "live":
        raise SystemExit(f"devices.tsv {name}: no manual and no measurement.")
    if row["manual"] and not (row["revision"] and row["section"]):
        raise SystemExit(f"devices.tsv {name}: a manual without a revision or section.")
    if row["radix"] not in RADIX:
        raise SystemExit(f"devices.tsv {name}: unknown radix {row['radix']!r}")
    if row["unit"] not in UNIT:
        raise SystemExit(f"devices.tsv {name}: unknown unit {row['unit']!r}")
    if row["min_spec"] not in SPEC:
        raise SystemExit(f"devices.tsv {name}: unknown min_spec {row['min_spec']!r}")
    if row["min_spec"] == "short" and not row["code_short"]:
        raise SystemExit(f"devices.tsv {name}: min_spec is short but code_short is empty.")
    if row["min_spec"] == "long" and row["code_short"]:
        raise SystemExit(f"devices.tsv {name}: min_spec is long but a code_short is given.")
    for field in ("batch_ok", "random_ok", "monitor_ok", "block_ok"):
        if row[field] not in BOOL:
            raise SystemExit(f"devices.tsv {name}: {field} must be yes or no")


def render() -> str:
    rows = sorted(read_table("devices"), key=lambda r: r["name"])
    lines: list[str] = [HEADER.rstrip("\n")]
    for row in rows:
        check_row(row)
        name = row["name"]
        short = row["code_short"]
        lines.append(f"    {py_str(name)}: DeviceType(")
        lines.extend(kw_str("name", name, 8))
        lines.extend(kw_str("long_name", row["long_name"], 8))
        lines.extend(kw_raw("unit", UNIT[row["unit"]], 8))
        lines.extend(kw_raw("words_per_point", row["words_per_point"], 8))
        lines.extend(kw_str("ascii2", row["ascii2"], 8))
        lines.extend(kw_str("ascii4", row["ascii4"], 8))
        lines.extend(kw_raw("code_short", short if short else "None", 8))
        lines.extend(kw_raw("code_long", row["code_long"], 8))
        lines.extend(kw_raw("radix", RADIX[row["radix"]], 8))
        lines.extend(kw_raw("min_spec", SPEC[row["min_spec"]], 8))
        for field in ("batch_ok", "random_ok", "monitor_ok", "block_ok"):
            lines.extend(kw_raw(field, BOOL[row[field]], 8))
        lines.extend(kw_raw("provenance", f"Provenance.{row['provenance'].upper()}", 8))
        lines.extend(citation_lines(row, 8))
        lines.extend(measurement_lines(row, 8))
        lines.extend(kw_str("note", row["note"], 8))
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append('"""Device family name -> its wire coding. Keys are upper case."""')
    lines.append("")
    prefixes = sorted((r["name"] for r in rows), key=lambda n: (-len(n), n))
    lines.append("PREFIXES_LONGEST_FIRST: Final[tuple[str, ...]] = (")
    for prefix in prefixes:
        lines.append(f"    {py_str(prefix)},")
    lines.append(")")
    lines.append('"""Device prefixes, longest first.')
    lines.append("")
    lines.append("Address parsing MUST try these in order: SB, SW, STS, LCN and their")
    lines.append("relatives all begin with a letter that is itself a device. A parser that")
    lines.append('matches the shortest prefix reads "SB0" as step relay B0.')
    lines.append('"""')
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="rewrite the committed file")
    group.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv)

    generated = render()
    if args.stdout:
        sys.stdout.write(generated)
        return 0
    if args.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(generated, encoding="ascii", newline="\n")
        print(f"wrote {TARGET}")
        return 0
    if not TARGET.exists():
        print(f"{TARGET} does not exist; run: python tools/{Path(__file__).name} --write")
        return 1
    current = TARGET.read_text(encoding="ascii")
    if current == generated:
        print(f"{TARGET} is current")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"{TARGET} (committed)",
            tofile="regenerated from data/devices.tsv",
        )
    )
    print(f"\n{TARGET} is stale; run: python tools/{Path(__file__).name} --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
