"""The same calls as :class:`aslmp.client.Plc`, returning the transaction with the value.

@generated by ``tools/gen_timed.py`` from ``aslmp/client.py``. **Do not edit this file.**
Edit the method on ``Plc``, mark it ``@mirrored``, and run
``python tools/gen_timed.py --write``; CI asserts that regenerating is a byte-for-byte
no-op, which is what stops the two surfaces from drifting.

Layer 5, and a peer of :mod:`aslmp.client` rather than a layer above it: this module
imports the client, and ``Plc.timed`` resolves this one lazily on first use.

DESIGN.md graft G14. The primary surface returns bare values; this one returns
:class:`~aslmp.results.Reading` for a read and :class:`~aslmp.results.WriteAck` for a
write. Both are the same code: ``Plc._done`` and ``Plc._ack`` are one-line helpers on the
client whose only job is to be the seam a generator can cut along.

One consequence worth knowing: :class:`~aslmp.results.RandomReading` carries its own
``tx`` field (DESIGN.md section 2.6), so ``plc.timed.read_random(...)`` returns a
``Reading[RandomReading]`` whose ``.tx`` is the same object as its ``.value.tx``. The
uniformity is deliberate -- ``tests/unit/test_client.py`` asserts that the two surfaces
have identical public method names and parameter lists, and an exception carved out here
would be an exception to maintain by hand.
"""

from __future__ import annotations

import struct
from collections.abc import Sequence
from typing import Literal, overload

from aslmp.blocks.fields import check_reading
from aslmp.client import (
    Plc,
    _check_point_value,
    _check_writing,
    _fits,
    _from_words,
    _RawCommand,
    _SilentRawCommand,
    _string_words,
    _to_words,
)
from aslmp.commands.base import (
    AddressLike,
    WordOrder,
    boolean,
    codec_name,
    decoded,
    encoded,
    real,
    signed,
    unsigned,
)
from aslmp.commands.batch import ReadBits, ReadWords, WriteBits, WriteWords
from aslmp.commands.block import BlockSpec, BlockWrite, ReadBlocks, WriteBlocks
from aslmp.commands.info import DEFAULT_LOOPBACK, ClearError, ReadTypeName, SelfTest
from aslmp.commands.monitor import ExecuteMonitor, MonitorRegistration, RegisterMonitor
from aslmp.commands.random import RandomPoint, RandomWrite, ReadRandom, WriteRandom
from aslmp.errors import SlmpCapabilityError, SlmpConfigurationError
from aslmp.identity import (
    CpuDiagnostics,
    CpuIdentity,
    CpuStatus,
    cpu_diagnostics_points,
    cpu_status_command,
    decode_cpu_diagnostics,
    decode_cpu_status,
)
from aslmp.profile import Family
from aslmp.results import RandomReading, Reading, SplitReading, WriteAck
from aslmp.wire.raw import RawResponse

__all__ = ["TimedApi"]


class TimedApi:
    """``plc.timed``: every :class:`~aslmp.client.Plc` call, with its record attached.

    Not constructed directly. ``Plc.timed`` builds one on first use and caches it, so a
    control loop that reaches for it every cycle allocates nothing.
    """

    __slots__ = ("_plc",)

    def __init__(self, plc: Plc) -> None:
        self._plc = plc

    @property
    def plc(self) -> Plc:
        """The client these calls run on. The bare-value surface for the same socket."""
        return self._plc

    async def read_bit(self, address: AddressLike, /) -> Reading[bool]:
        """One bit device, as a ``bool``. ``0x0401`` in bit units."""
        values, tx = await self._plc._run(ReadBits(address, 1), mutates=False)
        return Reading(values[0], tx)

    async def read_i16(
        self,
        address: AddressLike,
        /,
        *,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> Reading[int]:
        """One register as a signed 16-bit integer.

        ``minimum``/``maximum`` are the per-call form of a block field's declared bounds:
        a promise **you** make about what may be in that register, enforced on the value
        that comes back. See :meth:`read_f32`, which is where the promise earns its keep.
        """
        words, tx = await self._plc._run(ReadWords(address, 1), mutates=False)
        value = signed(words[0], bits=16)
        check_reading(
            value,
            minimum,
            maximum,
            field="read_i16",
            address=address,
            registers=words,
            client=self._plc,
        )
        return Reading(value, tx)

    async def read_u16(
        self,
        address: AddressLike,
        /,
        *,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> Reading[int]:
        """One register as an unsigned 16-bit integer."""
        words, tx = await self._plc._run(ReadWords(address, 1), mutates=False)
        check_reading(
            words[0],
            minimum,
            maximum,
            field="read_u16",
            address=address,
            registers=words,
            client=self._plc,
        )
        return Reading(words[0], tx)

    async def read_i32(
        self,
        address: AddressLike,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> Reading[int]:
        """Two consecutive registers as a signed 32-bit integer."""
        words, tx = await self._plc._run(ReadWords(address, 2), mutates=False)
        raw = _from_words(words, self._plc._order(word_order))
        value = int(struct.unpack("<i", raw)[0])
        check_reading(
            value,
            minimum,
            maximum,
            field="read_i32",
            address=address,
            registers=words,
            client=self._plc,
        )
        return Reading(value, tx)

    async def read_u32(
        self,
        address: AddressLike,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> Reading[int]:
        """Two consecutive registers as an unsigned 32-bit integer."""
        words, tx = await self._plc._run(ReadWords(address, 2), mutates=False)
        raw = _from_words(words, self._plc._order(word_order))
        value = int(struct.unpack("<I", raw)[0])
        check_reading(
            value,
            minimum,
            maximum,
            field="read_u32",
            address=address,
            registers=words,
            client=self._plc,
        )
        return Reading(value, tx)

    async def read_f32(
        self,
        address: AddressLike,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> Reading[float]:
        """Two consecutive registers as one IEEE-754 single.

        Low word first, measured four ways on FX5U-32MT/DS fw 1.065: 1234.5 written as
        one double-word point put ``00 50 9A 44`` on the wire and read back
        ``D104 = 0x5000``, ``D105 = 0x449A`` (2026-09-06).

        ``minimum`` and ``maximum`` are optional plausibility bounds. A D register
        carries no type on the wire, so the *width* you ask for is never wrong and the
        *meaning* can be: two registers a PLC program writes as a ``REAL``, read here as
        a ``u32``, are a large plausible integer with end code ``0x0000``. This library
        will not guess which of the two it is looking at, and it will not sniff the
        bytes; it will hold the value to a range you declare and raise
        :class:`~aslmp.blocks.fields.SlmpImplausibleValueError` if it is outside.
        """
        words, tx = await self._plc._run(ReadWords(address, 2), mutates=False)
        raw = _from_words(words, self._plc._order(word_order))
        value = float(struct.unpack("<f", raw)[0])
        check_reading(
            value,
            minimum,
            maximum,
            field="read_f32",
            address=address,
            registers=words,
            client=self._plc,
        )
        return Reading(value, tx)

    async def read_f64(
        self,
        address: AddressLike,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
    ) -> Reading[float]:
        """Four consecutive registers as one IEEE-754 double."""
        words, tx = await self._plc._run(ReadWords(address, 4), mutates=False)
        raw = _from_words(words, self._plc._order(word_order))
        value = float(struct.unpack("<d", raw)[0])
        check_reading(
            value,
            minimum,
            maximum,
            field="read_f64",
            address=address,
            registers=words,
            client=self._plc,
        )
        return Reading(value, tx)

    async def read_str(
        self, address: AddressLike, /, *, length: int, encoding: str = "ascii"
    ) -> Reading[str]:
        """``length`` **bytes** packed two per register, trimmed at the first NUL.

        ``length`` is required and is a count of BYTES, not of characters. It said
        "characters" here and in :meth:`write_str` for three revisions and was the byte
        window in every implementation, which is exactly how a ``shift_jis`` pair got cut
        in half: ``read_str('D110', length=3, encoding='shift_jis')`` over two registers
        holding ``0xA082 0xA282`` raised a bare ``UnicodeDecodeError`` (measured on
        FX5U-32MT/DS fw 1.065 from this host over TCP 5002, 2026-09-07). For ``ascii``
        and every other single-byte codec the two counts are the same number, which is
        why the wrong word survived. The window is now named for what it is and the cut
        is refused by :func:`~aslmp.commands.base.decoded` rather than escaping as a
        Python exception.

        ``length`` is required for the same reason ``--as`` is. A string region has no
        in-band length, so the alternatives to naming it are reading a fixed maximum --
        which returns the next field's bytes -- or scanning for a NUL, which is a second
        round trip whose answer can change between the two.

        The codec name is checked **before** the request is built, so a typo costs no
        round trip -- the same point in the call the write half has always checked it at.
        """
        count = _string_words(length)
        what = f"read_str({address}, length={length})"
        codec_name(encoding, what=what)
        words, tx = await self._plc._run(ReadWords(address, count), mutates=False)
        raw = struct.pack(f"<{len(words)}H", *words)[:length]
        text = decoded(raw.split(b"\x00", 1)[0], encoding=encoding, what=what)
        return Reading(text, tx)

    async def write_bit(
        self, address: AddressLike, value: bool, /, *, verify: bool = False
    ) -> WriteAck:
        """One bit device. ``0x1401`` in bit units. ``value`` is ``True`` or ``False``."""
        checked = boolean(value, what=f"write_bit({address})")
        _written, tx = await self._plc._run(WriteBits(address, (checked,)), mutates=True)
        if verify:
            back = await self._plc.read_bit(address)
            self._plc._check(back, value, what=f"write_bit({address})")
        return WriteAck(1, tx)

    async def write_i16(
        self,
        address: AddressLike,
        value: int,
        /,
        *,
        minimum: float | None = None,
        maximum: float | None = None,
        verify: bool = False,
    ) -> WriteAck:
        """One register from a signed 16-bit integer. Never masked, never clamped.

        ``minimum``/``maximum`` are the same declared range :meth:`read_i16` holds a
        reading to, enforced here **before** anything is sent. See :meth:`write_f32`.
        """
        word = unsigned(value, bits=16, what=f"write_i16({address})", signed_field=True)
        _check_writing(
            value, minimum, maximum, field="write_i16", kind="i16", address=address
        )
        _written, tx = await self._plc._run(WriteWords(address, (word,)), mutates=True)
        if verify:
            back = await self._plc.read_i16(address)
            self._plc._check(back, value, what=f"write_i16({address})")
        return WriteAck(1, tx)

    async def write_u16(
        self,
        address: AddressLike,
        value: int,
        /,
        *,
        minimum: float | None = None,
        maximum: float | None = None,
        verify: bool = False,
    ) -> WriteAck:
        """One register from an unsigned 16-bit integer.

        ``minimum``/``maximum`` are the same declared range :meth:`read_u16` holds a
        reading to, enforced here **before** anything is sent. See :meth:`write_f32`.
        """
        word = unsigned(value, bits=16, what=f"write_u16({address})", signed_field=False)
        _check_writing(
            value, minimum, maximum, field="write_u16", kind="u16", address=address
        )
        _written, tx = await self._plc._run(WriteWords(address, (word,)), mutates=True)
        if verify:
            back = await self._plc.read_u16(address)
            self._plc._check(back, word, what=f"write_u16({address})")
        return WriteAck(1, tx)

    async def write_i32(
        self,
        address: AddressLike,
        value: int,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
        verify: bool = False,
    ) -> WriteAck:
        """Two registers from a signed 32-bit integer.

        ``minimum``/``maximum`` are the same declared range :meth:`read_i32` holds a
        reading to, enforced here **before** anything is sent. See :meth:`write_f32`.
        """
        order = self._plc._order(word_order)
        words = _to_words(struct.pack("<I", _fits(value, signed_field=True, address=address)),
                          order)
        _check_writing(
            value, minimum, maximum, field="write_i32", kind="i32", address=address
        )
        _written, tx = await self._plc._run(WriteWords(address, words), mutates=True)
        if verify:
            read_back = await self._plc.read_i32(address, word_order=order)
            self._plc._check(read_back, value, what=f"write_i32({address})")
        return WriteAck(2, tx)

    async def write_u32(
        self,
        address: AddressLike,
        value: int,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
        verify: bool = False,
    ) -> WriteAck:
        """Two registers from an unsigned 32-bit integer.

        ``minimum``/``maximum`` are the same declared range :meth:`read_u32` holds a
        reading to, enforced here **before** anything is sent. See :meth:`write_f32`.
        """
        order = self._plc._order(word_order)
        words = _to_words(struct.pack("<I", _fits(value, signed_field=False, address=address)),
                          order)
        _check_writing(
            value, minimum, maximum, field="write_u32", kind="u32", address=address
        )
        _written, tx = await self._plc._run(WriteWords(address, words), mutates=True)
        if verify:
            read_back = await self._plc.read_u32(address, word_order=order)
            self._plc._check(read_back, value, what=f"write_u32({address})")
        return WriteAck(2, tx)

    async def write_f32(
        self,
        address: AddressLike,
        value: float,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
        verify: bool = False,
    ) -> WriteAck:
        """Two registers from one IEEE-754 single, low word first.

        ``minimum`` and ``maximum`` are the write-side half of :meth:`read_f32`'s
        plausibility bounds: the same declared range, judged **before** anything is sent,
        raising :class:`~aslmp.errors.SlmpValueRangeError` rather than the read's
        :class:`~aslmp.blocks.fields.SlmpImplausibleValueError` because here there is
        nothing to answer. A bound is a statement about what may be in that register and
        a write is the other way something gets there -- which is why a *block* field has
        had both directions since bounds existed, and why this per-call form having only
        the read half was the same defect one door along. Nothing is clamped to fit: a
        setpoint quietly pulled back to the top of its range is a different setpoint
        written to the plant.
        """
        order = self._plc._order(word_order)
        packed = struct.pack("<f", real(value, bits=32, what=f"write_f32({address})"))
        _check_writing(
            value, minimum, maximum, field="write_f32", kind="f32", address=address
        )
        _written, tx = await self._plc._run(
            WriteWords(address, _to_words(packed, order)), mutates=True
        )
        if verify:
            read_back = await self._plc.read_f32(address, word_order=order)
            rounded = float(struct.unpack("<f", packed)[0])
            self._plc._check(read_back, rounded, what=f"write_f32({address})")
        return WriteAck(2, tx)

    async def write_f64(
        self,
        address: AddressLike,
        value: float,
        /,
        *,
        word_order: WordOrder | None = None,
        minimum: float | None = None,
        maximum: float | None = None,
        verify: bool = False,
    ) -> WriteAck:
        """Four registers from one IEEE-754 double.

        ``minimum``/``maximum`` are the same declared range :meth:`read_f64` holds a
        reading to, enforced here **before** anything is sent. See :meth:`write_f32`.
        """
        order = self._plc._order(word_order)
        packed = struct.pack("<d", real(value, bits=64, what=f"write_f64({address})"))
        words = _to_words(packed, order)
        _check_writing(
            value, minimum, maximum, field="write_f64", kind="f64", address=address
        )
        _written, tx = await self._plc._run(WriteWords(address, words), mutates=True)
        if verify:
            read_back = await self._plc.read_f64(address, word_order=order)
            self._plc._check(read_back, float(value), what=f"write_f64({address})")
        return WriteAck(4, tx)

    async def write_str(
        self,
        address: AddressLike,
        value: str,
        /,
        *,
        length: int,
        encoding: str = "ascii",
        verify: bool = False,
    ) -> WriteAck:
        """``length`` **bytes**, NUL padded, two per register.

        ``length`` is a count of BYTES, not of characters, and always was: the comparison
        below is against ``len(raw)``, the encoded length. It is named for that now, on
        both halves of the pair -- see :meth:`read_str`, where the same wrong word cut a
        ``shift_jis`` character in half on the way back.

        A string longer than ``length`` raises rather than being truncated to fit: a
        silently shortened part number is a wrong part number.

        ``value`` must be a ``str`` that ``encoding`` can actually carry. Passing
        ``b"x"``, a character ASCII has no room for, or a codec name that does not exist
        raises inside the DESIGN section 3.1 tree
        (:func:`~aslmp.commands.base.encoded`) rather than as the bare
        ``AttributeError``, ``UnicodeEncodeError`` or ``LookupError`` that
        ``value.encode(encoding)`` used to let out of a write path.
        :meth:`read_str` now refuses the mirror-image failures through
        :func:`~aslmp.commands.base.decoded`; it did not when this paragraph was written,
        which is the whole reason the enforcement test in
        ``tests/unit/test_read_write_symmetry.py`` exists.
        """
        raw = encoded(value, encoding=encoding, what=f"write_str({address})")
        if len(raw) > length:
            raise SlmpConfigurationError(
                f"write_str({address}, length={length}) was given {len(raw)} byte(s) of "
                f"{encoding}. Nothing here truncates to fit."
            )
        padded = raw.ljust(_string_words(length) * 2, b"\x00")
        words = struct.unpack(f"<{len(padded) // 2}H", padded)
        _written, tx = await self._plc._run(WriteWords(address, words), mutates=True)
        if verify:
            read_back = await self._plc.read_str(address, length=length, encoding=encoding)
            self._plc._check(read_back, value, what=f"write_str({address})")
        return WriteAck(len(words), tx)

    async def read_words(self, address: AddressLike, /, count: int) -> Reading[tuple[int, ...]]:
        """``count`` consecutive registers, as unsigned words. Batch ceiling 960 words."""
        words, tx = await self._plc._run(ReadWords(address, count), mutates=False)
        return Reading(words, tx)

    async def read_bits(self, address: AddressLike, /, count: int) -> Reading[tuple[bool, ...]]:
        """``count`` consecutive bit devices. Batch ceiling 3584 bits on an FX5U."""
        values, tx = await self._plc._run(ReadBits(address, count), mutates=False)
        return Reading(values, tx)

    async def read_f32_array(
        self, address: AddressLike, /, count: int, *, word_order: WordOrder | None = None
    ) -> Reading[tuple[float, ...]]:
        """``count`` IEEE-754 singles from ``2 * count`` consecutive registers."""
        order = self._plc._order(word_order)
        words, tx = await self._plc._run(ReadWords(address, 2 * count), mutates=False)
        values = tuple(
            float(struct.unpack("<f", _from_words(words[index : index + 2], order))[0])
            for index in range(0, len(words), 2)
        )
        return Reading(values, tx)

    async def write_words(self, address: AddressLike, values: Sequence[int], /) -> WriteAck:
        """``len(values)`` consecutive registers.

        A raw register names no type, so ``-1`` and ``65535`` are the same sixteen bits
        and both are accepted; ``70000`` and ``1.5`` are not, and both raise
        :class:`~aslmp.errors.SlmpValueRangeError` before anything is built.
        """
        checked = tuple(
            # signed_field=None: this is the raw-register door, and it is the only
            # kind of write that has no declared type to enforce.
            unsigned(
                value,
                bits=16,
                what=f"write_words({address}) value {index}",
                signed_field=None,
            )
            for index, value in enumerate(values)
        )
        _written, tx = await self._plc._run(WriteWords(address, checked), mutates=True)
        return WriteAck(len(checked), tx)

    async def write_bits(self, address: AddressLike, values: Sequence[bool], /) -> WriteAck:
        """``len(values)`` consecutive bit devices. Each is ``True`` or ``False``, exactly.

        ``[2]``, ``[-1]`` and ``["yes"]`` raise rather than all writing a 1: Python's
        truthiness is not the PLC's, and a caller who passed the wrong element of a list
        would otherwise never find out.
        """
        checked = tuple(
            boolean(value, what=f"write_bits({address}) value {index}")
            for index, value in enumerate(values)
        )
        _written, tx = await self._plc._run(WriteBits(address, checked), mutates=True)
        return WriteAck(len(checked), tx)

    async def write_f32_array(
        self,
        address: AddressLike,
        values: Sequence[float],
        /,
        *,
        word_order: WordOrder | None = None,
    ) -> WriteAck:
        """``len(values)`` IEEE-754 singles into ``2 * len(values)`` registers."""
        order = self._plc._order(word_order)
        words: list[int] = []
        for index, value in enumerate(values):
            checked = real(value, bits=32, what=f"write_f32_array({address}) value {index}")
            words.extend(_to_words(struct.pack("<f", checked), order))
        _written, tx = await self._plc._run(WriteWords(address, tuple(words)), mutates=True)
        return WriteAck(len(words), tx)

    @overload
    async def read_random(
        self, points: Sequence[RandomPoint], /, *, allow_split: Literal[False] = False
    ) -> Reading[RandomReading]: ...

    @overload
    async def read_random(
        self, points: Sequence[RandomPoint], /, *, allow_split: Literal[True]
    ) -> Reading[RandomReading] | Reading[SplitReading]: ...

    async def read_random(
        self, points: Sequence[RandomPoint], /, *, allow_split: bool = False
    ) -> Reading[RandomReading] | Reading[SplitReading]:
        """Scattered word and double-word points in **one** snapshot. Results POSITIONAL.

        The wire demands every word specification before every double-word one and
        carries no framing between the groups; the command sorts, encodes, decodes and
        restores the caller's order, so ``reading[2]`` is the third point as written.

        ``allow_split=True`` returns a **different type** when the request does not fit
        the CPU's point ceiling, because splitting destroys the single-snapshot atomicity
        that is the entire reason to send a ``0403``. With the default
        ``allow_split=False`` an over-budget request raises
        :class:`~aslmp.errors.SlmpPointLimitError` and nothing is sent.
        """
        requested = tuple(points)
        if allow_split and len(requested) > self._plc._random_ceiling():
            split = await self._plc._read_random_split(requested)
            return Reading(split, split.transactions[-1])
        resolved = tuple(point.resolve(self._plc._ctx) for point in requested)
        values, tx = await self._plc._run(ReadRandom(requested), mutates=False)
        return Reading(RandomReading(resolved, values, tx), tx)

    async def write_random(self, writes: Sequence[RandomWrite], /) -> WriteAck:
        """Scattered word and double-word writes in one ``1402``.

        The budget is weighted, not flat: ``word x 12 + dword x 14 <= 1920`` on an FX5U
        (measured). A flat count is wrong in both directions -- 160 word points fit and
        138 double-word points do not.

        Each value is held to the type **its own point names**: an ``i16`` point given
        40000 raises rather than putting ``0x9C40`` on the wire for the PLC to read back
        as ``-25536``, exactly as :meth:`write_i16` does. A ``u16`` point given ``-1``
        raises too, exactly as :meth:`write_u16` does -- it did not until the pair was
        looked at together. ``RandomWrite(word('D101', kind='u16'), -1)`` masked to
        ``0xFFFF`` and this method sent it, and ``D101`` read back 65535 on the bench
        (FX5U-32MT/DS fw 1.065 from this host over TCP 5002, 2026-09-07) from a call the
        typed door refuses outright. The raw-register door, where ``-1`` and ``65535``
        are the same sixteen bits, is :meth:`write_words`, and it is the only one.
        """
        checked = tuple(writes)
        for index, item in enumerate(checked):
            _check_point_value(item, index)
        _written, tx = await self._plc._run(WriteRandom(checked), mutates=True)
        return WriteAck(len(checked), tx)

    async def read_blocks(
        self, blocks: Sequence[BlockSpec], /
    ) -> Reading[tuple[tuple[int, ...], ...]]:
        """Several contiguous runs in one frame; one tuple of words per block, in order."""
        values, tx = await self._plc._run(ReadBlocks(tuple(blocks)), mutates=False)
        return Reading(values, tx)

    async def write_blocks(self, blocks: Sequence[BlockWrite], /) -> WriteAck:
        """Several contiguous runs written in one frame."""
        _written, tx = await self._plc._run(WriteBlocks(tuple(blocks)), mutates=True)
        return WriteAck(sum(block.points for block in blocks), tx)

    async def monitor_register(
        self, points: Sequence[RandomPoint], /
    ) -> Reading[MonitorRegistration]:
        """``0801``: register a point list for later ``0802`` reads.

        Refused pre-transport on an iQ-F, which answers ``0xC059`` -- not the ``0xC05D``
        "monitor not registered" a reader of the generic reference would expect. It is
        never emulated with a ``0403``: substituting a different command that returns
        similar-looking data is exactly the silent recovery this library forbids.

        The returned registration is stamped with **this** client, and
        :meth:`monitor_read` will execute it on no other (:meth:`_own_registration`).
        """
        registration, tx = await self._plc._run(RegisterMonitor(tuple(points)), mutates=True)
        return Reading(registration.owned_by(self._plc), tx)

    async def monitor_read(
        self, registration: MonitorRegistration, /
    ) -> Reading[RandomReading]:
        """``0802``: read the registered list. Positional, exactly like ``read_random``.

        The registration must have been made by **this** client; one made by another
        raises :class:`~aslmp.errors.SlmpConfigurationError` and sends nothing
        (:meth:`_own_registration`).
        """
        owned = self._plc._own_registration(registration, "monitor_read()")
        values, tx = await self._plc._run(ExecuteMonitor(owned), mutates=False)
        resolved = tuple(point.resolve(self._plc._ctx) for point in owned.points)
        return Reading(RandomReading(resolved, values, tx), tx)

    async def self_test(self, payload: bytes = DEFAULT_LOOPBACK, /) -> Reading[bytes]:
        """``0619``: ask the module to echo ``payload``. Zero side effects.

        The default is ``b"ABCD"`` -- ``41 42 43 44``, the exact bytes proven on the
        bench. Both manuals restrict loopback data to ``'0'``-``'9'`` and ``'A'``-``'F'``
        and ``Codec.loopback_payload_ok`` enforces it, against our own defaults included.
        """
        echo, tx = await self._plc._run(SelfTest(payload), mutates=False)
        return Reading(echo, tx)

    async def ping(self) -> Reading[float]:
        """One ``0619`` round trip, in milliseconds. The liveness probe.

        Zero side effects, and its latency equals a real read (~7 ms on FX5U-32MT/DS fw
        1.065), which is what makes it a usable baseline rather than a lower bound.
        """
        nonce = self._plc._counters.probes_sent & 0xFFFF
        self._plc._counters.probes_sent += 1
        _echo, tx = await self._plc._run(
            SelfTest(b"0619" + f"{nonce:04X}".encode("ascii")), mutates=False
        )
        return Reading(tx.timing.wire_ms, tx)

    async def read_type_name(self) -> Reading[CpuIdentity]:
        """``0101``: which CPU is on the other end, with its family resolved.

        The family comes from the profile that claims the model code, never from parsing
        the name: the name is a marketing string whose shape has changed between
        families, and the model code is what decides whether ``Y20`` is output 16 or 32.
        """
        type_name, tx = await self._plc._run(ReadTypeName(), mutates=False)
        return Reading(CpuIdentity.of(type_name), tx)

    async def read_cpu_status(self) -> Reading[CpuStatus]:
        """The CPU operating status, from SD203 read as an ordinary word.

        SLMP has no "what state are you in" command. An undocumented value raises rather
        than being rounded to the nearest state: "the CPU is stopped" is not something to
        say on no evidence.
        """
        words, tx = await self._plc._run(cpu_status_command(), mutates=False)
        return Reading(decode_cpu_status(words), tx)

    async def read_diagnostics(self) -> Reading[CpuDiagnostics]:
        """State, error flag, latest error code and its stamp, and the clock: one ``0403``.

        :meth:`read_cpu_status` answers RUN or STOP. This answers "and is anything wrong",
        which a CPU can be while it runs: on 2026-09-25 the bench FX5U reported an error
        continuously in RUN for a module left unpowered, and ``aslmp probe`` called the
        connection healthy throughout -- correctly, because the connection was.

        **iQ-F only.** The register layout was measured on an FX5U
        (:data:`~aslmp.identity.CPU_DIAGNOSTICS_MEASURED`) and on no other family, so
        any other profile gets :class:`~aslmp.errors.SlmpCapabilityError` and nothing is
        sent. :meth:`read_cpu_status` reads SD203 on every family.
        """
        if self._plc._profile.family is not Family.IQ_F:
            raise SlmpCapabilityError(
                f"read_diagnostics() reads a special-register layout measured on an iQ-F "
                f"CPU and on no other family; {self._plc._profile.key} is "
                f"{self._plc._profile.family.value}, and guessing that its clock and error "
                f"registers sit in the same places, in the same coding, is not something "
                f"this library does. read_cpu_status() reads SD203 on every family. "
                f"Nothing was sent."
            )
        values, tx = await self._plc._run(ReadRandom(cpu_diagnostics_points()), mutates=False)
        return Reading(decode_cpu_diagnostics(values), tx)

    async def clear_error(self) -> WriteAck:
        """``1617``: clear the own-station error code and the error LED."""
        _nothing, tx = await self._plc._run(ClearError(), mutates=True)
        return WriteAck(0, tx)

    @overload
    async def raw_command(
        self,
        command: int,
        subcommand: int,
        payload: bytes = b"",
        /,
        *,
        mutates: bool = True,
        expect_response: Literal[True] = True,
    ) -> Reading[RawResponse]: ...

    @overload
    async def raw_command(
        self,
        command: int,
        subcommand: int,
        payload: bytes = b"",
        /,
        *,
        mutates: bool = True,
        expect_response: Literal[False],
    ) -> Reading[None]: ...

    async def raw_command(
        self,
        command: int,
        subcommand: int,
        payload: bytes = b"",
        /,
        *,
        mutates: bool = True,
        expect_response: bool = True,
    ) -> Reading[RawResponse] | Reading[None]:
        """Send arbitrary command bytes. **Bypasses command validation and nothing else.**

        The frame, the ``L`` guard, the one-in-flight gate, the end-code raise and the
        transaction record all still apply. It exists because this CPU accepted requests
        its own manual forbids, and a library that can only send what it approves of
        cannot be used to find out what a CPU really does.

        ``expect_response=False`` is overloaded to return ``None`` rather than widening
        the normal return type, for the same reason ``allow_split`` is: a caller who did
        not ask for silence never has to narrow a union. It also **retires the connection**
        -- see :meth:`Connection.retire_after_silent_exchange`.

        **The one thing it does not bypass is the remote-control interlock.** ``0x1001``
        through ``0x1006`` are refused here unless the client was built with
        ``allow_remote_control=True``, exactly as :attr:`remote` refuses them. Validation
        is a property of the *command* and the interlock is a property of the *client*, so
        ``_RawCommand.validate()`` being a deliberate no-op cannot be the whole story:
        before this check, ``plc.remote.run()`` raised and ``plc.raw_command(0x1001, 0)``
        halted or started the same machine on the same client (verified on FX5U-32MT/DS
        fw 1.065, 2026-09-07). An escape hatch for finding out what a CPU really does is
        not an escape hatch from "this library can stop a running plant".
        """
        self._plc._require_interlock_for(command)
        if not expect_response:
            silent = _SilentRawCommand(command, subcommand, payload, mutates)
            return Reading(None, await self._plc._run_silent(silent, mutates=mutates))
        response, tx = await self._plc._run(
            _RawCommand(command, subcommand, payload, mutates), mutates=mutates
        )
        return Reading(response, tx)
